---

# This file wires together the variables of the various components (roles) used by the playbook.
#
# Roles used by playbook are kept independent of one another as much as possible.
# To deliver a turnkey fully-featured server, this playbook needs
# to connect them all together. It does so by overriding role variables.

######################################################################
#
#  base
#
######################################################################

######################################################################
#
#  dns: dnscrypt-proxy default enabled, without adblocking
#
######################################################################
dns_local_service_ip_seed: "{{ vps_seed + ansible_fqdn }}"

######################################################################
#
#  firewalld: default enabled
#
######################################################################
firewalld_webserver_enabled: "{{ true if searxng_enabled or snikket_enabled else false }}"
firewalld_snikket_enabled: "{{ true if snikket_enabled else false }}"
#
# exposes vars from wireguard role
firewalld_vpn_enabled: "{{ true if wireguard_enabled else false }}"
# exposes vars from dns role
firewalld_dnscrypt_proxy_enabled: "{{ true if dns_encryption_enabled or dns_adblocking_enabled else false }}"
#
firewalld_vpn_port: "{{ wireguard_port }}"
firewalld_vpn_ports_to_redirect: "{{ wireguard_ports_to_redirect }}"
firewalld_vpn_network_ipv4: "{{ wireguard_network_ipv4 }}"
firewalld_vpn_network_ipv6: "{{ wireguard_network_ipv6 }}"

######################################################################
#
#  wireguard: default enabled
#
######################################################################
dns_enabled: "{{ true if wireguard_enabled else false }}"
wireguard_dns_servers: >-
  {% if dns_adblocking_enabled | default(false) | bool or dns_encryption_enabled | default(false) | bool %}
  {{ dns_local_service_ip }}{{ ', ' + dns_local_service_ipv6 if vps_ipv6_support else '' }}
  {% else %}
  {% for host in dns_servers.ipv4 %}{{ host }}{% if not loop.last %},{% endif %}{% endfor %}{% if vps_ipv6_support %},{% for host in dns_servers.ipv6 %}{{ host }}{% if not loop.last %},{% endif %}{% endfor %}{% endif %}
  {% endif %}

######################################################################
#
#  docker: enabled conditionally
#
######################################################################
docker_enabled: "{{ true if searxng_enabled or snikket_enabled else false }}"

######################################################################
#
#  searxng
#
######################################################################

######################################################################
#
#  snikket
#
######################################################################

######################################################################
#
#  terminal software
#
######################################################################

######################################################################
#
#  caddy: enabled conditionally
#
######################################################################
caddy_enabled: "{{ true if searxng_enabled or snikket_enabled else false }}"
# caddy file uses:
# searxng_enabled
# searxng_hostname
# searxng_public
# vps_home_ipv4 vps_home_ipv6 wireguard_network_ipv4 wireguard_network_ipv6
