---

# This file wires together the variables of the various components (roles) used by the playbook.
#
# Roles used by playbook are kept independent of one another as much as possible.
# To deliver a turnkey fully-featured server, this playbook needs
# to connect them all together. It does so by overriding role variables.

######################################################################
#
#  base
#
######################################################################

######################################################################
#
#  dns: dnscrypt-proxy default enabled, without adblocking
#
######################################################################
dns_local_service_ip_seed: "{{ vps_seed + ansible_fqdn }}"

######################################################################
#
#  firewalld: default enabled
#
######################################################################
firewalld_webserver_enabled: "{{ true if searxng_enabled else false }}"
# exposes vars from wireguard role
firewalld_vpn_enabled: "{{ true if wireguard_enabled else false }}"
# exposes vars from dns role
firewalld_dnscrypt_proxy_enabled: "{{ true if dns_encryption_enabled or dns_adblocking_enabled else false }}"
#
firewalld_vpn_port: "{{ wireguard_port }}"
firewalld_vpn_network_ipv4: "{{ wireguard_network_ipv4 }}"
firewalld_vpn_network_ipv6: "{{ wireguard_network_ipv6 }}"

######################################################################
#
#  nftables: deprecated
#
######################################################################
#
# nftables_webserver_enabled: "{{ true if searxng_enabled else false }}"
# # exposes vars from wireguard role
# nftables_wireguard_enabled: "{{ true if wireguard_enabled else false }}"
# # exposes vars from dns role
# nftables_dnscrypt_proxy_enabled: "{{ true if dns_encryption_enabled or dns_adblocking_enabled else false }}"

######################################################################
#
#  wireguard: default enabled
#
######################################################################
dns_enabled: "{{ true if wireguard_enabled else false }}"
wireguard_dns_servers: >-
  {% if dns_adblocking_enabled | default(false) | bool or dns_encryption_enabled | default(false) | bool %}
  {{ dns_local_service_ip }}{{ ', ' + dns_local_service_ipv6 if vps_ipv6_support else '' }}
  {% else %}
  {% for host in dns_servers.ipv4 %}{{ host }}{% if not loop.last %},{% endif %}{% endfor %}{% if vps_ipv6_support %},{% for host in dns_servers.ipv6 %}{{ host }}{% if not loop.last %},{% endif %}{% endfor %}{% endif %}
  {% endif %}

######################################################################
#
#  docker: must be enabled by its services
#
######################################################################

######################################################################
#
#  caddy: must be enabled by its services
#
######################################################################

######################################################################
#
#  searxng
#
######################################################################
caddy_enabled: "{{ true if searxng_enabled else false }}"
docker_enabled: "{{ true if searxng_enabled else false }}"
searxng_rootless: "{{ true if docker_rootless_enabled else false }}"
searxng_install_dir: "{{ searxng_install_dir_rootless if docker_rootless_enabled else searxng_install_dir_systemwide }}"
searxng_systemd_dir: "{{ searxng_systemd_dir_rootless if docker_rootless_enabled else searxng_systemd_dir_systemwide }}"

######################################################################
#
#  terminal software
#
######################################################################
terminal_software_add_docker_rootless_to_zsh: "{{ true if docker_rootless_enabled and terminal_software_zsh_enabled else false }}"
