---
- name: Remove parts
  ansible.builtin.file:
    path: /etc/wireguard/parts
    state: absent

- name: Restart wireguard
  ansible.builtin.systemd:
    name: "{{ wireguard_service_name }}"
    state: restarted
    daemon_reload: true
