---
- name: restart wireguard
  ansible.builtin.systemd:
    name: "{{ wireguard_service_name }}"
    state: restarted
    daemon_reload: true

- name: Save private keys
  ansible.builtin.import_tasks: save_private_keys.yml

- name: Save preshared keys
  ansible.builtin.import_tasks: save_preshared_keys.yml
