---

# 1. Tags: -> Selecting which tasks are considered to run:
# Invoke without tags: Everything is considered
# Using tag inheritance with import_role: All tags in the role will be tagged with the tag
# assigned to the import_role task
# 2 When: -> Decides if tasks actually runs
# Using when on import_role task: All tasks in the role will be executed and skipped
# Also relevant:
# https://yaml-multiline.info/

# TODO:
# vps_ipv6 not working on hetzner
# Readme and repo on github

- name: Configure the server and install required software
  hosts: vps_servers
  gather_facts: true
  become: true
  tasks:

    - name: Import facts role
      ansible.builtin.import_role:
        name: facts
      tags: [always]

    - name: Import base role
      ansible.builtin.import_role:
        name: base
      tags: [base]

    - name: Import firewalld role
      ansible.builtin.import_role:
        name: firewalld
      when: firewalld_enabled
      tags: [firewalld]

    - name: Import dns role
      ansible.builtin.import_role:
        name: dns
      when: dns_enabled
      tags: [dns]

    - name: Import wireguard role
      ansible.builtin.import_role:
        name: wireguard
      when: wireguard_enabled
      tags: [wireguard]

    - name: Import terminal software role
      ansible.builtin.import_role:
        name: terminal_software
      when: terminal_software_enabled
      tags: [terminal_software]

    - name: Import docker role
      ansible.builtin.import_role:
        name: docker
      when: docker_enabled
      tags: [docker]

    - name: Import caddy role
      ansible.builtin.import_role:
        name: caddy
      when: caddy_enabled
      tags: [caddy]

    - name: Import searxng role
      ansible.builtin.import_role:
        name: searxng
      when: searxng_enabled
      tags: [searxng]

    - name: Import snikket role
      ansible.builtin.import_role:
        name: snikket
      when: snikket_enabled
      tags: [snikket]
