---
- name: Configure the server and install required software
  hosts: wgvps_servers
  gather_facts: true
  become: true

  # This used to be in common debian.yml
  # The task includes an option with an undefined variable. The error was: 'ansible_default_ipv4' is undefined
  # Gather facts should run...
  # - name: Gather facts
  #   ansible.builtin.setup:

  tasks:
    - name: Import common role
      ansible.builtin.import_role:
        name: common
      tags: common

    - name: Import dns role
      ansible.builtin.import_role:
        name: dns
      when:
        - wgvps_dns_adblocking or
          dns_encryption
      tags: dns

    - name: Import wireguard role
      ansible.builtin.import_role:
        name: wireguard
      when: wireguard_enabled
      tags: wireguard

    - name: Import searxng role
      ansible.builtin.import_role:
        name: searxng
      when: searxng_enabled
      tags: searxng
