---
# TODO: tag setup-all is redundant. Same as performing without any tags
- name: Configure the server and install required software
  hosts: vps_servers
  gather_facts: true
  become: true
  tasks:
    - name: Import base role
      ansible.builtin.import_role:
        name: base
    - name: Import nftables role
      ansible.builtin.import_role:
        name: nftables
    - name: Import dnscrypt-proxy role
      ansible.builtin.import_role:
        name: dnscrypt-proxy
    - name: Import wireguard role
      ansible.builtin.import_role:
        name: wireguard
    - name: Import searxng role
      ansible.builtin.import_role:
        name: searxng
