---
# 1. Tags: -> Selecting which tasks are considered to run:
# Invoke without tags: Everything runs
# Using tag inheritance with import_role: All tags in the role will be tagged with the tag
# assigned to the import_role task
# 2 When: -> Decides if tasks actually runs
# Using when on import_role task: All tasks in the role will be executed and skipped
# Also relevant:
# https://yaml-multiline.info/
#
# TODO:
# Check if roles contain all variables
# Reorganize vars.yml, add must change vars to the top
# Cleanup unused algo vars
# Add example config
# Evaluate:
#   wireguard_port_avoid redirects to port_actual
#   between_clients?
#   hash_limit
# Firewalld for better defaults and docker integration
# Searx: filter engines in use
# .zshenv should be content, not copy
# Test python env
# fail2ban instead of custom ssh port
# ssh: unknown terminal alacritty
# Think of a name for the repo
# Readme and repo on github

- name: Configure the server and install required software
  hosts: vps_servers
  gather_facts: true
  become: true
  tasks:

    - name: Import base role
      ansible.builtin.import_role:
        name: base
      tags: [base]

    - name: Import nftables role
      ansible.builtin.import_role:
        name: nftables
      when: nftables_enabled
      tags: [nftables]

    - name: Import dnscrypt-proxy role
      ansible.builtin.import_role:
        name: dnscrypt-proxy
      when:
        - dns_adblocking_enabled or
          dns_encryption_enabled
      tags: [dnscrypt-proxy]

    - name: Import wireguard role
      ansible.builtin.import_role:
        name: wireguard
      when: wireguard_enabled
      tags: [wireguard]

    - name: Import terminal role
      ansible.builtin.import_role:
        name: terminal
      when: terminal_enabled
      tags: [terminal]

    - name: Import docker role
      ansible.builtin.import_role:
        name: docker
      when: docker_enabled
      tags: [docker]

    - name: Import caddy role
      ansible.builtin.import_role:
        name: caddy
      when: caddy_enabled
      tags: [caddy]

    - name: Import searxng role
      ansible.builtin.import_role:
        name: searxng
      when: searxng_enabled
      become: "{{ not searxng_rootless }}"
      tags: [searxng]
