---
# - name: Import scratch2 role
#   ansible.builtin.import_role:
#     name: scratch2
#   tags: [scratch, scratch2]

# - name: Import scratch1 role
#   ansible.builtin.import_role:
#     name: scratch1
#   tags: [scratch, scratch1]
#
# 1. Selecting which tasks are considered to run:
# Invoke without tags: Everything runs
# Using tag inheritance with import_role: All tags in the role will be tagged with the tag
# assigned to the import_role task
# 2 Once tasks are selected to run:
# Using when on import_role task: All tasks in the role will be executed and skipped
# TODO: Also inheritance? The role always imported
# Especially useful when playbook is invoked without tags
#
- name: Configure the server and install required software
  hosts: vps_servers
  gather_facts: true
  become: true
  tasks:

    # contains tag upgrade-all
    - name: Import base role
      ansible.builtin.import_role:
        name: base
      tags: [base]

    - name: Import terminal role
      ansible.builtin.import_role:
        name: terminal
      when: terminal_enabled
      tags: [terminal]

    - name: Import nftables role
      ansible.builtin.import_role:
        name: nftables
      when: nftables_enabled
      tags: [nftables]

    - name: Import dnscrypt-proxy role
      ansible.builtin.import_role:
        name: dnscrypt-proxy
      when:
        - dns_adblocking_enabled or
          dns_encryption_enabled
      tags: [dnscrypt-proxy]

    # contains tag update-users
    - name: Import wireguard role
      ansible.builtin.import_role:
        name: wireguard
      when: wireguard_enabled
      tags: [wireguard]

    - name: Import docker role
      ansible.builtin.import_role:
        name: docker
      when: docker_enabled
      tags: [docker]

    - name: Import searxng role
      ansible.builtin.import_role:
        name: searxng
      when: searxng_enabled
      become: "{{ not searxng_rootless }}"
      tags: [searxng]
