---
- name: Configure the server and install required software
  hosts: wgvps_servers
  gather_facts: false
  become: true

  # vars_files:
  # - config.cfg

  tasks:
    - name: Import common role
      ansible.builtin.import_role:
        name: common
      tags: common

# - import_role:
#     name: dns
#   when:
#     - algo_dns_adblocking or
#       dns_encryption
#   tags: dns

# - import_role:
#     name: wireguard
#   when: wireguard_enabled
#   tags: wireguard
