---

# ipv6: digital ocean -> when creating a droplet, also activate ipv6
# reference config on server: /etc/network/interfaces/cloud_init

- name: "Sanity check"
  import_playbook: playbooks/sanity_check.yml
  tags:
    - sanity

- name: "Cloud setup"
  import_playbook: playbooks/cloud.yml
  tags:
    - cloud

- name: "Obtain ansible controller ip"
  import_playbook: playbooks/obtain_ip.yml
  tags:
    - obtain_ip

- name: "Add ansible controller ip to all hosts in group"
  import_playbook: playbooks/process_ip.yml
  tags:
    - process_ip

# - name: Add firewall before proceeding to main playbook
#   hosts: vps_servers
#   gather_facts: true
#   become: true
#   tasks:
#     - name: Ensure firewalld installed
#       ansible.builtin.apt:
#         name: firewalld
#         state: present
#         update_cache: true
#       when: firewalld_enabled

#     - name: Ensure firewalld systemd service runs
#       ansible.builtin.systemd:
#         name: firewalld
#         daemon_reload: true
#         enabled: true
#         state: started
#       when: firewalld_enabled
