---

# - name: Change ip6
#   ansible.builtin.lineinfile:
#     dest: inventory/host_vars/www.drieberen.xyz/vars.yml
#     regexp: 'vps_home_ipv6: '
#     line: "vps_home_ipv6: {{ ipify_public_ip }}"
#     state: present
#   connection: local

# - name: Debug home ip 1
#   ansible.builtin.debug:
#     msg: "{{ ansible_env['SSH_CLIENT'].split() | first }}"

# - name: Debug ip adress used by ssh connection
#   ansible.builtin.debug: var=hostvars[inventory_hostname]['ansible_env'].SSH_CONNECTION.split(' ')[2]

# - name: Debug ip4 adress default
#   # ansible.builtin.debug: var=hostvars[inventory_hostname]['ansible_default_ipv4']['address']
#   # ansible.builtin.debug: var=hostvars[inventory_hostname]['ansible_default_ipv4']['alias']
#   ansible.builtin.debug: var=ansible_default_ipv4.alias

# - name: Debug ip4 adress eth0
#   ansible.builtin.debug: var=ansible_eth0.ipv4.address
#   # ansible.builtin.debug: var=ansible_eth0

# - name: Debug ip4 adress enp0s3
#   ansible.builtin.debug: var=ansible_enp0s3.ipv4.address

# - name: Debug ip6 adress default
#   ansible.builtin.debug: var=hostvars[inventory_hostname]['ansible_default_ipv6']['address']

# https://docs.ansible.com/ansible/latest/user_guide/playbooks_vars_facts.html
- name: Configure the server and install required software
  hosts: vps_servers
  gather_facts: true
  # Do not use become, otherwise SSH_CLIENT fails on undefined and SSH_CONNECTION.split results in undefined
  become: false

  # group_names:
  # - vps_servers
  # groups:
  #   all:
  #   - test.domain.xyz
  #   ungrouped: []
  #   vps_servers:
  #   - test.domain.xyz
  # inventory_dir: /home/user/playbooks/wgvps/inventory
  # inventory_file: /home/user/playbooks/wgvps/inventory/hosts
  # inventory_hostname: test.domain.xyz
  tasks:
    # - name: Debug inventory_hostname
    #   ansible.builtin.debug:
    #     msg: "{{ hostvars[inventory_hostname] }}"

    - name: Debug inventory_hosts
      ansible.builtin.debug:
        msg: "{{ inventory_dir + '/host_vars/' + item + '/vars.yml'}}"
      with_items:
        - "{{ hostvars[inventory_hostname]['groups']['all'] }}"
      delegate_to: localhost
