---

- name: Standalone ansible template invoked by vps script
  hosts: vps_servers
  gather_facts: true
  become: true
  tasks:

    - name: Standalone tasks
      ansible.builtin.include_role:
        name: "{{ standalone_role }}"
        tasks_from: "{{ standalone_from }}"
