---

- name: Add and delete wireguard users
  hosts: vps_servers
  gather_facts: true
  become: true
  vars:
    booleans_map:
      Y: true
      y: true
  tasks:

    - name: Ask for confirmation
      ansible.builtin.pause:
        prompt: |
          Please note:
            Advise: Only change the users listed in playbook var "wireguard_users"
            The following will be kept:
              The existing config on the host
              Existing client configs that remain present in playbook var "wireguard_users"

          Users specified: {{ wireguard_users }}
          Are you sure(y/N)?
      register: confirmation_result

    - name: Translate answer into fact
      ansible.builtin.set_fact:
        confirmation: "{{ booleans_map[confirmation_result.user_input] | default(false) }}"

    - name: User aborted
      ansible.builtin.fail:
        msg: Stopped processing
      when: not confirmation

    - name: Start processing
      block:
        - name: Import facts role
          ansible.builtin.import_role:
            name: facts

        - name: Wireguard uses variables from dns role
          ansible.builtin.import_role:
            name: dns
          when: false

        - name: Import wireguard role
          ansible.builtin.import_role:
            name: wireguard
      when:
        - wireguard_enabled
        - confirmation
