---

# All wireguard users will have to import a new config...

- name: Remove existing wireguard setup and rebuild from scratch
  hosts: vps_servers
  gather_facts: true
  become: true
  vars:
    booleans_map:
      Y: true
      y: true
  tasks:

    - name: Ask for confirmation
      ansible.builtin.pause:
        prompt: |
          This will remove all existing users and build new configs for
          all users in list 'wireguard_users'
          Are you sure(y/N)?
      register: _answer

    - name: Debug answer
      ansible.builtin.debug:
        msg: a"{{ _answer }}"b

    - name: Translate answer into fact
      ansible.builtin.set_fact:
        wireguard_rotate_confirmed: >-
          {%- if _answer.user_input is defined %}
            {{ booleans_map[_answer.user_input] | default(false) }}
          {%- else %}false{% endif %}

    # - block:

    #     - name: Import facts role
    #       ansible.builtin.import_role:
    #         name: facts

    #     - name: Find files to delete on server
    #       ansible.builtin.find:
    #         paths: '/etc/wireguard'
    #         patterns:
    #           - '*.lock'
    #           - '*.conf'
    #       register: files_to_delete

    #     - name: Ensure server files are deleted
    #       ansible.builtin.file:
    #         dest: "{{ item.path }}"
    #         state: absent
    #       with_items:
    #         - "{{ files_to_delete.files }}"

    #     - name: Ensure all local wireguard configuration is removed
    #       ansible.builtin.file:
    #         dest: "{{ wireguard_config_path }}"
    #         state: absent
    #       delegate_to: localhost
    #       become: false

    #     # wireguard references dns variables
    #     - name: Import dns role
    #       ansible.builtin.import_role:
    #         name: dns
    #       when: false

    #     - name: Import wireguard role
    #       ansible.builtin.import_role:
    #         name: wireguard
    #   when:
    #     - wireguard_rotate_confirmed
    #     - wireguard_enabled
