---

###############################################################################
# Modifiable:
#
# Not stable yet with systemd --user. No start on reboot:
# Rootless worked with:
docker_rootless_enabled: false

###############################################################################
# Not modifiable:
docker_enabled: false
# modifies zshrc:
docker_rootless_and_terminal_enabled: false
