---

# nvim 0.4.4
# build-essential: amongst others: make
- name: Ensure additional software is installed
  ansible.builtin.apt:
    name:
      - tmux
      - rsync
      - zsh
      - zsh-syntax-highlighting
      - zsh-autosuggestions
      - fzf
      - vim
      # - neovim
      - lua5.4
      - luarocks
      - build-essential
      - curl
      - wget
      - gnupg
      - pwgen
      - gawk
      - tree
      - exa
      - neofetch
      - fd-find
      - bc
      - ripgrep
      - apt-file
      - python3-pip
      - python-is-python3
    state: present
    update_cache: true

- name: Ensure the required directories exist
  ansible.builtin.file:
    dest: "{{ item }}"
    state: directory
    recurse: true
  with_items:
    - "~/builds"
    - "~/bin"
    - "~/.config/zsh"
    - "~/.config/tmux"
    - "~/.cache/zsh"
    - "~/.local/bin"
    - "~/.cargo/bin"
    - "~/.local/go/bin"
    - "~/go/bin"
  become: false

- name: Ensure necessary files are present
  ansible.builtin.copy:
    dest: "{{ item }}"
    mode: "0644"
    content: ''
  with_items:
    - "~/.cache/zsh/dummy-zcompdump-path-marker"
  when: terminal_software_zsh_enabled
  become: false

# archive mode is -rlptgoD (no -A,-X,-U,-N,-H)
# -r recursive
# -l links
# -p permissions
# -t modification times
# -g preserve group
# -o preserve owner(superuser only)
# -D --devices(preservice device files, superuser) --specials(preserve spefial files)
#
# some files(.zshenv) are changed on the host, do not overwrite these:
# --update -u skip files that are newer on the receiver
- name: Ensure personal repos are present in .config
  ansible.posix.synchronize:
    src: "{{ item }}"
    dest: "~/.config"
    mode: push
    rsync_opts:
      - "-u --exclude=.git"
  with_items:
    - "{{ terminal_software_personal_config_repos }}"
  become: false

- name: Ensure zsh .env in home folder
  ansible.builtin.copy:
    dest: "~/.zshenv"
    mode: "0644"
    content: |
      # Redirect
      export ZDOTDIR="$HOME/.config/zsh"
      . $ZDOTDIR/.zshenv
  when: terminal_software_zsh_enabled
  become: false

- name: Ensure git repos are cloned
  ansible.builtin.git:
    clone: true
    dest: "{{ item.folder }}"
    repo: "{{ item.repo }}"
    version: master
    update: false
    force: false
  with_items:
    - "{{ terminal_software_repos }}"
  become: false

- name: Ensure spaceship repo is cloned
  ansible.builtin.git:
    clone: true
    dest: "/opt/spaceship-prompt"
    repo: "{{ terminal_software_spaceship_repo }}"
    version: master
    update: false
    force: false
    depth: 1
  when: terminal_software_spaceship_enabled
  notify: link spaceship

- name: Ensure users shell is zsh
  ansible.builtin.user:
    name: "{{ vps_user }}"
    shell: /usr/bin/zsh
  when: terminal_software_zsh_enabled

- name: Force all notified handlers to run at this point, not waiting for normal sync points
  ansible.builtin.meta: flush_handlers
