---

# TODO: [WARNING]: reset_connection task does not support when conditional
# module_stderr: |-
#     Shared connection to test1.domein.xyz closed.
#   module_stdout: ""
#   msg: |-
#     MODULE FAILURE
#     See stdout/stderr for the exact error

# When in terminal one would use: newgrp docker
- name: reset connection
  ansible.builtin.meta:
    reset_connection
