---
- name: daemon reload
  ansible.builtin.systemd:
    daemon_reload: true

- name: restart dnscrypt-proxy
  ansible.builtin.systemd:
    name: dnscrypt-proxy
    state: restarted
    daemon_reload: true
