---

- name: restart systemd-resolved
  ansible.builtin.systemd:
    name: systemd-resolved
    state: restarted

- name: restart systemd-networkd
  ansible.builtin.systemd:
    name: systemd-networkd
    state: restarted
    daemon_reload: true

- name: restart dnscrypt-proxy
  ansible.builtin.systemd:
    name: dnscrypt-proxy
    state: restarted
    daemon_reload: true
