#! /bin/bash

# Change:
# vps_server ANSIBLE MANAGED BLOCK
# vps_server END ANSIBLE MANAGED BLOCK
# vps_peers ANSIBLE MANAGED BLOCK
# phone ANSIBLE MANAGED BLOCK
# phone END ANSIBLE MANAGED BLOCK
# desktop ANSIBLE MANAGED BLOCK
# desktop END ANSIBLE MANAGED BLOCK
# vps_peers END ANSIBLE MANAGED BLOCK
# Into:
# phone
# desktop

# Also: use || true
# Otherwise, a file with no peers results in a non zero return code

set -o pipefail
grep '^# .* ANSIBLE MANAGED BLOCK' "$1" | grep -E -v 'END|vps_server|vps_peers' | sed 's/# //g' | cut -d' ' -f1 || true
