---
###############################################################################
# Deploy WireGuard. WireGuard will listen on 51820/UDP.
# If the network blocks this port another port can be chosen.
# Be aware that 53/UDP (DNS) is blocked on some mobile data networks.

###############################################################################
# Modifiable:
wireguard_enabled: true
#
# Every device must have a unique user. There are 65,534 slots.
# Requirements: Escape leading 0's or only numbers in double quotes("000dan" or "123").
# Email addresses are not allowed
wireguard_users:
  - vpnuser
#
# If you're behind NAT or a firewall and you want to receive incoming connections long after network traffic has gone silent.
# This option will keep the "connection" open in the eyes of NAT.
# See: https://www.wireguard.com/quickstart/#nat-and-firewall-traversal-persistence
wireguard_persistentkeepalive: 0
#
# Reduce the MTU of the VPN tunnel
# The normal value is 1500, some providers use a smaller Maximum Transmission Unit
# If connections are unresponsive adjust this value
# The playbook will attempt to set this automatically based on your server,
# but if connections hang you might need to adjust this yourself.
wireguard_reduce_mtu: 0
#
# Disable logging when generating keys:
wireguard_no_log: true

###############################################################################
# Network configuration, modify with care, should not be needed
wireguard_interface: wg0
wireguard_service_name: "wg-quick@{{ wireguard_interface }}"
wireguard_port: 51820
# Activate redirection from other ports if network blocks the actual wireguard port.
# Some mobile networks block 53/UDP (DNS). Ensure the ports are not in use on the vps
# The ports will be prerouted to wireguard port, this will have some affect on performance
# wireguard_ports_to_redirect:
#   - 53
wireguard_ports_to_redirect: []
wireguard_network_ipv4: 10.49.0.0/16
wireguard_network_ipv6: 2001:db8:a160::/48
#

###############################################################################
# Folders and files, modify with care, should not be needed
#
wireguard_etc_path: "/etc/wireguard/"
# parts for server(containing private key) and client peers(contain preshared and public keys)
wireguard_parts_path: "/etc/wireguard/parts"
wireguard_host_config: "{{ wireguard_etc_path }}/{{ wireguard_interface }}.conf"

###############################################################################
# Local storage, modify with care, should not be needed
#
wireguard_config_path: "configs/{{ wireguard_host_ip }}/wireguard/"
wireguard_checksum_file: "{{ wireguard_config_path }}{{ wireguard_interface }}.sha256"

###############################################################################
# Not modifiable:
#
wireguard_host_ip_index: 1
wireguard_peers_ip_index_start: 2
# Previously ip_subject_alt_name: '', set in tasks
wireguard_host_ip: "{{ ansible_default_ipv4.address }}"
# Overridden in group_vars:
wireguard_dns_servers:
