---
- name: Adblock script created
  ansible.builtin.template:
    src: adblock.sh.j2
    dest: /usr/local/sbin/adblock.sh
    owner: root
    group: "{{ root_group|default('root') }}"
    mode: 0755

# Range causes the playbook to always report a change:
- name: Adblock script added to cron
  ansible.builtin.cron:
    name: Adblock hosts update
    # minute: "{{ range(0, 60) | random }}"
    # hour: "{{ range(0, 24) | random }}"
    minute: "10"
    hour: "23"
    job: /usr/local/sbin/adblock.sh
    user: root
    state: present

- name: Update adblock hosts
  ansible.builtin.command: /usr/local/sbin/adblock.sh
  changed_when: false

- name: dnscrypt-proxy ip-blacklist configured
  ansible.builtin.template:
    src: ip-blacklist.txt.j2
    dest: "{{ config_prefix|default('/') }}etc/dnscrypt-proxy/ip-blacklist.txt"
    mode: 0644
  notify:
    - restart dnscrypt-proxy

- name: dnscrypt-proxy configured
  ansible.builtin.template:
    src: dnscrypt-proxy.toml.j2
    dest: "{{ config_prefix|default('/') }}etc/dnscrypt-proxy/dnscrypt-proxy.toml"
    mode: 0644
  notify:
    - restart dnscrypt-proxy
