---

# only needed for dnscrypt-proxy
- name: Loopback for services configured
  ansible.builtin.template:
    src: 10-vps-lo100.network.j2
    dest: /etc/systemd/network/10-vps-lo100.network
    mode: 0644
  notify:
    - restart systemd-networkd

- name: Include install tasks
  ansible.builtin.import_tasks: install-dnscrypt-proxy.yml

- name: Include configurations tasks
  ansible.builtin.import_tasks: configure-dnscrypt-proxy.yml

- name: Force all notified handlers to run at this point, not waiting for normal sync points
  ansible.builtin.meta: flush_handlers

- name: dnscrypt-proxy enabled and started
  ansible.builtin.systemd:
    name: dnscrypt-proxy
    state: started
    enabled: true
