---

# The main limit is Certificates per Registered Domain (50 per week)
# example searx1.domain.org, searx2.domain.org
#
# Renewals Duplicate Certificate limit of 5 per week
# https://letsencrypt.org/docs/rate-limits/

- name: Ensure local caddy folder exists
  ansible.builtin.file:
    path: "{{ caddy_results_path }}"
    state: directory
    mode: 0755

- name: Archive caddy certificates directory
  community.general.archive:
    path: "{{ caddy_dir }}/.local"
    dest: "{{ caddy_dir }}/{{ caddy_certs_backup_name }}"
    owner: caddy
    group: caddy
    remove: false
    format: tar
    mode: 0600

- name: Fetch
  ansible.builtin.fetch:
    src: "{{ caddy_dir }}/{{ caddy_certs_backup_name }}"
    fail_on_missing: true
    flat: true
    dest: "{{ caddy_results_path }}/"

- name: Remove backup from server
  ansible.builtin.file:
    path: "{{ caddy_dir }}/{{ caddy_certs_backup_name }}"
    state: absent
