---
- name: Ensure nftables installed
  ansible.builtin.apt:
    name: nftables
    state: present
    update_cache: true
  tags:
    - setup-all
    - nftables

- name: Ensure nftables configured
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0755
  with_items:
    - {src: nftables.conf.j2, dest: /etc/nftables.conf}
  notify:
    - restart nftables
  tags:
    - setup-all
    - nftables

- name: Ensure nftables systemd service runs
  ansible.builtin.systemd:
    name: nftables
    daemon_reload: true
    enabled: true
    state: started
  tags:
    - setup-all
    - nftables
