---
dns_encryption_enabled: false
dns_adblocking_enabled: false
adblock_lists: []

# DNS servers which will be used if 'dns_encryption_enabled' is 'true'. Multiple
# providers may be specified, but avoid mixing providers that filter results
# (like Cisco) with those that don't (like Cloudflare) or you could get
# inconsistent results. The list of available public providers can be found
# here:
# https://github.com/DNSCrypt/dnscrypt-resolvers/blob/master/v2/public-resolvers.md
dnscrypt_servers: []

custom_server_stamps: ''

# Randomly generated IP address for the local dns resolver
# As of Ansible version 2.3, it’s also possible to initialize the random number
# generator from a seed. This way, you can create random-but-idempotent numbers:
local_service_ip: ''
local_service_ipv6: ''
