---

###############################################################################
# Modifiable:
###############################################################################
#

###############################################################################
# Not modifiable:
firewalld_enabled: true
# ports 80 and 443 to the world:
firewalld_webserver_enabled: false
# port 53 on dnscrypt proxy local ip
firewalld_dnscrypt_proxy_enabled: false
#
# Not recommended, still untested. Samba on wireguard.
# For the moment, samba software is not installed
firewalld_samba_enabled: false
#
# Vps:
firewalld_vpn_enabled: false
firewalld_vpn_port: ''
firewalld_vpn_ports_to_redirect: []
firewalld_vpn_network_ipv4: ''
firewalld_vpn_network_ipv6: ''
#
# Entities:
fw_zone_admin: admin
fw_zone_public: publicvps
fw_zone_vpn: vpn
fw_service_vpn: wireguard
fw_policy_vpn_to_world: vpnToWorld
#
# Entities ipsets
# See: ipsets.yml
#
# Entities dynamic collections:
fw_zones_active: []
fw_ipsets_active: []
