---

###############################################################################
# Modifiable:
###############################################################################
#

###############################################################################
# Not modifiable:
firewalld_enabled: true
# ports 80 and 443 to the world:
firewalld_webserver_enabled: false
# port 53 on dnscrypt proxy local ip
firewalld_dnscrypt_proxy_enabled: false
#
# Not recommended, still untested. Samba on wireguard.
# For the moment, samba software is not installed
firewalld_samba_enabled: false
#
# Vps:
firewalld_vps_enabled: false
firewalld_vps_port: ''
firewalld_vps_network_ipv4: ''
firewalld_vps_network_ipv6: ''
#
# Entities:
fw_zone_admin: admin
fw_zone_public: publicvps
fw_zone_vps: vps
fw_service_vps: wireguard
fw_policy_vps: vpsToWorld
#
# Entities ipsets
# See: ipsets.yml
#
# Entities dynamic collections:
fw_zones_active: []
fw_ipsets_active_active: []
