---

# Entities ipset
fw_ipset_admin:
  zone: "{{ fw_zone_admin }}"
  template: 'admin_ipset.xml.j2'
  dest: 'admin_ipfour.xml'
  name: 'admin_ipfour'
  config:
    description: The ipset for the adminzone, ipv4
    family: inet
    type: net
    entries:
      - "{{ vps_home_ipv4 }}"
fw_ipset_admin_ipsix:
  zone: "{{ fw_zone_admin }}"
  template: 'admin_ipset.xml.j2'
  dest: 'admin_ipsix.xml'
  name: 'admin_ipsix'
  config:
    description: The ipset for the adminzone, ipv6
    family: inet6
    type: net
    entries:
      - "{{ vps_home_ipv6 }}"
fw_ipset_vpn:
  zone: "{{ fw_zone_vpn }}"
  template: 'vpn_ipset.xml.j2'
  dest: 'vpn_ipfour.xml'
  name: 'vpn_ipfour'
  config:
    description: The ipset for the vpn zone, ipv4
    family: inet
    type: net
    entries:
      - "{{ firewalld_vpn_network_ipv4 }}"
fw_ipset_vpn_ipsix:
  zone: "{{ fw_zone_vpn }}"
  template: 'vpn_ipset.xml.j2'
  dest: 'vpn_ipsix.xml'
  name: 'vpn_ipsix'
  config:
    description: The ipset for the vpn zone, ipv6
    family: inet6
    type: net
    entries:
      - "{{ firewalld_vpn_network_ipv6 }}"
