---

# nvim 0.4.4
# build-essential: amongst others: make
- name: Ensure additional software is installed
  ansible.builtin.apt:
    name:
      - tmux
      - rsync
      - zsh
      - zsh-syntax-highlighting
      - zsh-autosuggestions
      - fzf
      - vim
      # - neovim
      - lua5.4
      - luarocks
      - htop
      - build-essential
      - curl
      - wget
      - gnupg
      - pwgen
      - gawk
      - tree
      - exa
      - neofetch
      - fd-find
      - bc
      - ripgrep
      - apt-file
      - python3-pip
      - python-is-python3
    state: present
    update_cache: true

- name: Ensure the required directories exist
  ansible.builtin.file:
    dest: "{{ item }}"
    state: directory
    recurse: true
  with_items:
    - "~/.config/zsh"
    - "~/.config/tmux"
    - "~/builds"
    - "~/.cache/zsh"
    - "~/.local/bin"
    - "~/.local/go/bin"
    - "~/go/bin"
    - "~/.cargo/bin"
    - "~/bin"
  become: false

- name: Ensure necessary files are present
  ansible.builtin.copy:
    dest: "{{ item }}"
    mode: "0644"
    content: ''
  with_items:
    - "~/.cache/zsh/dummy-zcompdump-path-marker"
  become: false

- name: Ensure personal repos are present in .config
  ansible.posix.synchronize:
    src: "{{ item }}"
    dest: "~/.config"
    mode: push
    rsync_opts:
      - "--exclude=.git"
  with_items:
    - "{{ terminal_dot_config_repos }}"
  become: false

- name: Ensure zsh .env in home folder
  ansible.builtin.copy:
    src: .zshenv
    dest: "~/.zshenv"
    mode: "0644"
  become: false

- name: Ensure git repos are cloned
  ansible.builtin.git:
    clone: true
    dest: "{{ item.folder }}"
    repo: "{{ item.repo }}"
    version: master
    update: false
    force: false
  with_items:
    - "{{ terminal_repos }}"
  become: false

- name: Ensure spaceship repo is cloned
  ansible.builtin.git:
    clone: true
    dest: "/opt/spaceship-prompt"
    repo: "{{ terminal_spaceship_repo }}"
    version: master
    update: false
    force: false
    depth: 1
  notify: link spaceship

- name: Ensure users shell is zsh
  ansible.builtin.user:
    name: "{{ vps_user }}"
    shell: /usr/bin/zsh
