---

###############################################################################
# Modifiable:
###############################################################################

###############################################################################
# Not modifiable:
firewalld_enabled: false
# ports 80 and 443 to the world:
firewalld_webserver_enabled: false
# starts using vars from wireguard role
firewalld_wireguard_enabled: false
# starts using vars from dnscrypt-proxy role
firewalld_dnscrypt_proxy_enabled: false
#
firewalld_custom_admin_zone: admin
firewalld_custom_public_zone: publicvps
firewalld_custom_vps_zone: vps
firewalld_custom_zones:
  - "{{ firewalld_custom_admin_zone }}"
  - "{{ firewalld_custom_public_zone }}"
#
firewalld_admin_ipset_ipfour:
  template: 'admin_ipset.xml.j2'
  dest: 'admin_ipfour.xml'
  name: 'admin_ipfour'
  use: true
  config:
    description: The ipset for the adminzone, ipv4
    family: inet
    type: net
    entries:
      - "{{ vps_home_ipv4 }}"
#
firewalld_admin_ipset_ipsix:
  template: 'admin_ipset.xml.j2'
  dest: 'admin_ipsix.xml'
  name: 'admin_ipsix'
  use: "{{ vps_ipv6_support }}"
  config:
    description: The ipset for the adminzone, ipv6
    family: inet6
    type: net
    entries:
      - "{{ vps_home_ipv6 }}"
#
firewalld_vps_ipset_ipfour: ''
#
firewalld_vps_ipset_ipsix: ''
#
# TODO: Not implemented: Traffic between wireguard clients, something to have?
# Block traffic between connected clients. Change this to false to enable
# connected clients to reach each other, as well as other computers on the
# same LAN as your Algo server (i.e. the "road warrior" setup). In this
# case, you may also want to enable SMB/CIFS and NETBIOS traffic below.
firewalld_between_clients_drop:
#
# TODO: Not implemented: Traffic between wireguard clients, something to have?
# Block SMB/CIFS traffic
firewalld_block_smb:
#
# TODO: Not implemented: Traffic between wireguard clients, something to have?
# Block NETBIOS traffic
firewalld_block_netbios:
