---

# https://blog.mohag.net/2018/05/managing-firewalld-ipsets-and-services.html
# example nft output
# set test {
#         type ipv4_addr
#         elements = { 1.2.3.4 }
# }

- name: Ensure admin ipv4 set is bound
  ansible.posix.firewalld:
    zone: admin
    permanent: true
    source: ipset:admin_ipfour
    state: enabled
  notify: reload firewalld

- name: Ensure admin ipv6 set is bound
  ansible.posix.firewalld:
    zone: admin
    permanent: true
    source: ipset:admin_ipsix
    state: enabled
  when: vps_ipv6_support
  notify: reload firewalld

- name: Ensure admin zone allows wireguard
  ansible.posix.firewalld:
    zone: admin
    permanent: true
    service: wireguard
    state: enabled
  notify: reload firewalld
  when: firewalld_wireguard_enabled

- name: Ensure admin zone allows http https
  ansible.posix.firewalld:
    zone: admin
    permanent: true
    service: "{{ item }}"
    state: enabled
  with_items:
    - http
    - https
  notify: reload firewalld
  when: firewalld_webserver_enabled

# Reason of existance: only allow ssh for the admin
- name: Ensure admin zone allows ssh
  ansible.posix.firewalld:
    zone: admin
    permanent: true
    service: ssh
    state: enabled
  notify: reload firewalld
