---

- name: Ensure ip sets are bound
  ansible.posix.firewalld:
    zone: "{{ item.zone }}"
    permanent: true
    source: "{{ 'ipset:' + item.name }}"
    state: enabled
  loop: "{{ fw_ipsets_active }}"
  notify: reload firewalld

- name: Ensure ipv4 interface is bound
  ansible.posix.firewalld:
    zone: "{{ fw_zone_public }}"
    permanent: true
    interface: "{{ ansible_default_ipv4['interface'] }}"
    state: enabled
  when: fw_zones_active | intersect([fw_zone_public])
  notify: reload firewalld

- name: Ensure ipv6 interface is bound
  ansible.posix.firewalld:
    zone: "{{ fw_zone_public }}"
    permanent: true
    interface: "{{ ansible_default_ipv6['interface'] }}"
    state: enabled
  when: vps_ipv6_support and fw_zones_active | intersect([fw_zone_public])
  notify: reload firewalld
