---

- name: Ensure ip sets are bound
  ansible.posix.firewalld:
    zone: "{{ item.zone }}"
    permanent: true
    source: "{{ 'ipset:' + item.name }}"
    state: enabled
  loop: "{{ firewalld_custom_ipsets }}"
  notify: reload firewalld

- name: Ensure interfaces are bound
  ansible.posix.firewalld:
    zone: publicvps
    permanent: true
    interface: "{{ item.interface }}"
    state: enabled
  when: item.use
  loop:
    - {use: true, interface: "{{ ansible_default_ipv4['interface'] }}"}
    - {use: "{{ vps_ipv6_support }}", interface: "{{ ansible_default_ipv6['interface'] }}"}
  notify: reload firewalld
