---

- name: Ensure firewalld factory reset is present for development
  ansible.builtin.copy:
    dest: /root/factory_reset_firewalld.sh
    mode: 0744
    content: |
      #!/bin/bash
      firewall-cmd --set-default-zone=public
      firewall-cmd --permanent --delete-zone="{{ firewalld_custom_admin_zone }}"
      firewall-cmd --permanent --delete-zone="{{ firewalld_custom_public_zone }}"
      firewall-cmd --permanent --delete-zone="{{ firewalld_custom_vps_zone }}"
      firewall-cmd --permanent --delete-ipset=admin_ipfour
      firewall-cmd --permanent --delete-ipset=admin_ipsix
      firewall-cmd --permanent --delete-ipset=vps_ipfour
      firewall-cmd --permanent --delete-ipset=vps_ipsix
      firewall-cmd --permanent --delete-policy=vpsToWorld
      firewall-cmd --reload
