---

- name: Ensure firewalld factory reset is present for development
  ansible.builtin.copy:
    dest: /root/factory_reset_firewalld.sh
    mode: 0744
    content: |
      #!/bin/bash
      firewall-cmd --set-default-zone=public
      firewall-cmd --permanent --delete-zone="{{ fw_zone_admin }}"
      firewall-cmd --permanent --delete-zone="{{ fw_zone_public }}"
      firewall-cmd --permanent --delete-zone="{{ fw_zone_vpn }}"
      firewall-cmd --permanent --delete-service="{{ fw_service_vpn }}"
      firewall-cmd --permanent --delete-policy="{{ fw_policy_vpn_to_world }}"
      firewall-cmd --permanent --delete-ipset="{{ fw_ipset_admin.name }}"
      firewall-cmd --permanent --delete-ipset="{{ fw_ipset_admin_ipsix.name }}"
      firewall-cmd --permanent --delete-ipset="{{ fw_ipset_vpn.name }}"
      firewall-cmd --permanent --delete-ipset="{{ fw_ipset_vpn_ipsix.name }}"
      firewall-cmd --reload
