---
# See tutorials: https://www.procustodibus.com/, but: prevent zonedrifting
# https://firewalld.org/2020/01/allowzonedrifting
# useful commands:
# ip -brief address show
# nmcli connecton show
# ss -tn | grep :22, find the ip in use by ssh
# sudo nmcli connection modify "<mywireless>" connection.zone home ( on client )
# firewall-cmd --get-default-zone firewall-cmd --get-active-zones firewall-cmd --get-ipsets firewall-cmd --get-policies
# default zone listing: firewall-cmd --list-all
# firewall-cmd --info-zone=admin firewall-cmd --info-ipset=admin_ipfour
# firewall-cmd --info-policy=vpsToWorld firewall-cmd --list-all-policies

- name: Import facts tasks
  ansible.builtin.import_tasks: main_facts.yml

- name: Import setup tasks
  ansible.builtin.import_tasks: main_setup.yml

- name: ++++ Ensure that new entities are reloaded in one sweep
  ansible.builtin.meta: flush_handlers

- name: Import config tasks
  ansible.builtin.import_tasks: main_config.yml

# Gven a clean install, until here, the runtime is still connected to the default public zone,
# allowing only dhcpv6-client and ssh to the world
- name: ++++ Ensure that applied sources and services are reloaded in one sweep
  ansible.builtin.meta: flush_handlers

- name: Import change default zone tasks
  ansible.builtin.import_tasks: main_change_default_zone.yml

# Script for development:
# - name: Import factory reset script for development tasks
#   ansible.builtin.import_tasks: factory_reset_script.yml
