---

- name: Capture default zone
  ansible.builtin.shell: |
    set -o pipefail && \
    firewall-cmd --get-default-zone | grep -w -c publicvps || true
  args:
    executable: /bin/bash
  register: defaultzone_result
  changed_when: false

# The set-default-zone command applies to both runtime and permanent
- name: Ensure publicvps is the default zone
  ansible.builtin.shell: |
    firewall-cmd --set-default-zone=publicvps
  args:
    executable: /bin/bash
  when: defaultzone_result.stdout == '0'
