---

- name: Ensure firewalld and nftables are installed
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - nftables
    - firewalld

- name: Ensure nftables systemd service is disabled and masked
  ansible.builtin.systemd:
    name: nftables
    daemon_reload: true
    enabled: false
    masked: true

- name: Ensure firewalld systemd service is enabled and started
  ansible.builtin.systemd:
    name: firewalld
    daemon_reload: true
    state: started
    enabled: true

- name: Ensure firewalld factory reset is present for development
  ansible.builtin.copy:
    dest: /root/factory_reset_firewalld.sh
    mode: 0744
    content: |
      #!/bin/bash
      firewall-cmd --permanent --delete-zone=admin
      firewall-cmd --permanent --delete-zone=publicvps
      firewall-cmd --permanent --delete-zone=vps
      firewall-cmd --permanent --delete-ipset=admin_ipfour
      firewall-cmd --permanent --delete-ipset=admin_ipsix
      firewall-cmd --permanent --delete-policy=vpsToWorld
      firewall-cmd --reload

# zone: admin
- name: Import admin tasks
  ansible.builtin.import_tasks: admin.yml

# zone: publicvps
- name: Import public tasks
  ansible.builtin.import_tasks: public.yml

# zone: vps
- name: Import wireguard tasks
  ansible.builtin.import_tasks: vps.yml
  when: firewalld_wireguard_enabled
