---

- name: attach sources and interfaces to zones
  ansible.builtin.import_tasks: attach_to_zones.yml

# To get the difference of 2 lists (items in 1 that don’t exist in 2):
- name: ssh service accept on all zones but fw_zone_public
  ansible.builtin.include_tasks: service_ssh_accept.yml
  loop: "{{ fw_zones_active | difference([fw_zone_public]) }}"

# To get the intersection of 2 lists (unique list of all items in both):
- name: ssh service drop on fw_zone_public
  ansible.builtin.include_tasks: service_ssh_drop.yml
  loop: "{{ fw_zones_active | intersect([fw_zone_public]) }}"

- name: http and https service on all zones
  ansible.builtin.include_tasks: service_web.yml
  loop: "{{ fw_zones_active }}"
  loop_control:
    loop_var: zone
  when: firewalld_webserver_enabled

- name: vps config, anticipate multiple vps zones
  block:
    - name: Facts, vps versus non-vps
      ansible.builtin.set_fact:
        fw_zones_vps: "{{ fw_zones_active | difference([fw_zone_admin,fw_zone_public]) }}"
        fw_zones_non_vps: "{{ fw_zones_active | intersect([fw_zone_admin,fw_zone_public]) }}"

    - name: vps service providing access to vps
      ansible.builtin.include_tasks: service_wireguard.yml
      loop: "{{ fw_zones_non_vps }}"

    - name: dns service on 'all' vps
      ansible.builtin.include_tasks: service_dns.yml
      loop: "{{ fw_zones_vps }}"
      when: firewalld_dnscrypt_proxy_enabled

    - name: vps forwarding and masquerading on 'all' vps
      ansible.builtin.include_tasks: attach_vps_to_world.yml
      loop: "{{ fw_zones_vps }}"
  when: firewalld_vps_enabled
