---
- name: attach sources and interfaces to zones
  ansible.builtin.import_tasks: attach_to_zones.yml

# To get the difference of 2 lists (items in 1 that don’t exist in 2):
# all zones but fw_zone_public:
- name: ssh service accept
  ansible.builtin.include_tasks: service_ssh_accept.yml
  loop: "{{ fw_zones_active | difference([fw_zone_public]) }}"

# To get the intersection of 2 lists (unique list of all items in both):
# only fw_zone_public:
- name: ssh service drop
  ansible.builtin.include_tasks: service_ssh_drop.yml
  loop: "{{ fw_zones_active | intersect([fw_zone_public]) }}"

# all zones:
- name: http and https service
  ansible.builtin.include_tasks: service_web.yml
  loop: "{{ fw_zones_active }}"
  loop_control:
    loop_var: zone
  when: firewalld_webserver_enabled

- name: vps config, anticipate multiple vps zones
  block:
    # non vps zones:
    - name: vps service entry point
      ansible.builtin.include_tasks: service_wireguard.yml
      loop: "{{ fw_zones_active | intersect([fw_zone_admin,fw_zone_public]) }}"

    # 'all' vps zones:
    - name: dns service
      ansible.builtin.include_tasks: service_dns.yml
      loop: "{{ fw_zones_active | difference([fw_zone_admin,fw_zone_public]) }}"
      when: firewalld_dnscrypt_proxy_enabled

    # 'all' vps zones:
    - name: vps forwarding and masquerading
      ansible.builtin.include_tasks: attach_vps_to_world.yml
      loop: "{{ fw_zones_active | difference([fw_zone_admin,fw_zone_public]) }}"
  when: firewalld_vps_enabled
