---
- name: attach sources to zones tasks
  ansible.builtin.import_tasks: connect_sources_to_zones.yml

- name: http and https service tasks
  ansible.builtin.include_tasks: service_web.yml
  loop: "{{ fw_zones_active }}"
  loop_control:
    loop_var: zone
  when: firewalld_webserver_enabled

- name: wireguard service tasks
  ansible.builtin.include_tasks: service_wireguard.yml
  loop: ["{{ firewalld_custom_admin_zone }}", "{{ firewalld_custom_public_zone }}"]
  loop_control:
    loop_var: zone
  when: firewalld_wireguard_enabled

- name: dns service tasks
  ansible.builtin.include_tasks: service_dns.yml
  loop: ["{{ firewalld_custom_vps_zone }}"]
  loop_control:
    loop_var: zone
  when:
    - firewalld_wireguard_enabled
    - firewalld_dnscrypt_proxy_enabled

- name: ssh service tasks
  ansible.builtin.import_tasks: service_ssh.yml

- name: vps forwarding and masquerading tasks
  ansible.builtin.import_tasks: connect_vps_to_world.yml
  when: firewalld_wireguard_enabled
