---
- name: Import attach sources to zones tasks
  ansible.builtin.import_tasks: connect_sources_to_zones.yml

- name: Import allow ssh service tasks
  ansible.builtin.import_tasks: service_ssh.yml

- name: Import allow http and https service tasks
  ansible.builtin.import_tasks: service_web.yml
  when: firewalld_webserver_enabled

- name: Import allow wireguard service tasks
  ansible.builtin.import_tasks: service_wireguard.yml
  when: firewalld_wireguard_enabled

- name: Import allow dns service tasks
  ansible.builtin.import_tasks: service_dns.yml
  when: firewalld_wireguard_enabled

- name: Import allow vps forwarding and masquerading tasks
  ansible.builtin.import_tasks: connect_vps_to_world.yml
  when: firewalld_wireguard_enabled
