---

# important commands:
# firewall-cmd --get-default-zone
# firewall-cmd --get-active-zones
# firewall-cmd --get-ipsets
# firewall-cmd --get-policies
#
# default zone listing:
# firewall-cmd --list-all
#
# other zones listing:
# firewall-cmd --info-zone=admin
# firewall-cmd --info-ipset=admin_ipfour
# firewall-cmd --info-policy=vpsToWorld
# firewall-cmd --list-all-policies

- name: Ensure firewalld and nftables are installed
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - nftables
    - firewalld

- name: Ensure nftables systemd service is disabled and masked
  ansible.builtin.systemd:
    name: nftables
    daemon_reload: true
    enabled: false
    masked: true

- name: Ensure firewalld systemd service is enabled and started
  ansible.builtin.systemd:
    name: firewalld
    daemon_reload: true
    state: started
    enabled: true

- name: Import needed entities tasks
  ansible.builtin.import_tasks: needed_entities.yml
- name: Ensure that new needed entities are reloaded only at this point
  ansible.builtin.meta: flush_handlers
- name: Import sources to zones tasks
  ansible.builtin.import_tasks: sources_to_zones.yml

# zone: admin
- name: Import admin tasks
  ansible.builtin.import_tasks: admin.yml

# zone: publicvps
- name: Import publicvps tasks
  ansible.builtin.import_tasks: publicvps.yml

# zone: vps
- name: Import wireguard tasks
  ansible.builtin.import_tasks: vps.yml
  when: firewalld_wireguard_enabled

# Note that up to this point, given a clean install, the runtime is
# still connected to the default zone, public, allowing only dhcpv6-client
# and ssh to the world
- name: Ensure that applied configurations are reloaded only at this point
  ansible.builtin.meta: flush_handlers

# zone: publicvps
- name: Import default zone tasks
  ansible.builtin.import_tasks: default_zone.yml

# script for development:
- name: Import script for development tasks
  ansible.builtin.import_tasks: factory_reset_script.yml
  when: false
