---

- name: Facts, all base zones
  ansible.builtin.set_fact:
    fw_zones_active: ["{{ fw_zone_admin }}", "{{ fw_zone_public }}"]

- name: Facts, all needed zones
  ansible.builtin.set_fact:
    fw_zones_active: "{{ fw_zones_active + [fw_zone_vps] }}"
  when: firewalld_wireguard_enabled

- name: Facts, base ipsets
  ansible.builtin.set_fact:
    firewalld_custom_ipsets: ["{{ firewalld_admin_ipset_ipfour }}"]

- name: Facts, add ipv6 to base ipsets
  ansible.builtin.set_fact:
    firewalld_custom_ipsets: "{{ firewalld_custom_ipsets + [firewalld_admin_ipset_ipsix] }}"
  when: vps_ipv6_support

- name: Facts, wireguard ipsets
  block:
    - name: Facts, add wireguard ipv4 to base ipsets
      ansible.builtin.set_fact:
        firewalld_custom_ipsets: "{{ firewalld_custom_ipsets + [firewalld_vps_ipset_ipfour] }}"

    - name: Facts, add wireguard ipv6 to base ipsets
      ansible.builtin.set_fact:
        firewalld_custom_ipsets: "{{ firewalld_custom_ipsets + [firewalld_vps_ipset_ipsix] }}"
      when: vps_ipv6_support
  when: firewalld_wireguard_enabled
