---

- name: Ensure publicvps zone allows wireguard
  ansible.posix.firewalld:
    zone: publicvps
    permanent: true
    service: wireguard
    state: enabled
  notify: reload firewalld
  when: firewalld_wireguard_enabled

- name: Ensure publicvps zone allows http https
  ansible.posix.firewalld:
    zone: publicvps
    permanent: true
    service: "{{ item }}"
    state: enabled
  with_items:
    - http
    - https
  notify: reload firewalld
  when: firewalld_webserver_enabled

- name: Ensure publicvps zone drops ssh
  ansible.posix.firewalld:
    zone: publicvps
    permanent: true
    rich_rule: 'rule priority=1 service name="ssh" drop'
    state: enabled
  notify: reload firewalld
