---

- name: Ensure ipv4 interface is added to publicvps zone
  ansible.posix.firewalld:
    zone: publicvps
    permanent: true
    interface: "{{ ansible_default_ipv4['interface'] }}"
    state: enabled
  notify: reload firewalld

- name: Ensure ipv6 interface is added to publicvps zone
  ansible.posix.firewalld:
    zone: publicvps
    permanent: true
    interface: "{{ ansible_default_ipv6['interface'] }}"
    state: enabled
  when: vps_ipv6_support
  notify: reload firewalld

- name: Ensure publicvps zone allows wireguard
  ansible.posix.firewalld:
    zone: publicvps
    permanent: true
    service: wireguard
    state: enabled
  notify: reload firewalld
  when: firewalld_wireguard_enabled

- name: Ensure publicvps zone allows http https
  ansible.posix.firewalld:
    zone: publicvps
    permanent: true
    service: "{{ item }}"
    state: enabled
  with_items:
    - http
    - https
  notify: reload firewalld
  when: firewalld_webserver_enabled

- name: Ensure publicvps zone drops ssh
  ansible.posix.firewalld:
    zone: publicvps
    permanent: true
    rich_rule: 'rule priority=1 service name="ssh" drop'
    state: enabled
  notify: reload firewalld
