---

- name: Ensure zones allow http https
  ansible.posix.firewalld:
    zone: "{{ zone }}"
    permanent: true
    service: "{{ item }}"
    state: enabled
  with_items:
    - http
    - https
  notify: reload firewalld
