---

- name: Ensure vps zone allows http https
  ansible.posix.firewalld:
    zone: vps
    permanent: true
    service: "{{ item }}"
    state: enabled
  with_items:
    - http
    - https
  when: firewalld_wireguard_enabled
  notify: reload firewalld

- name: Ensure publicvps zone allows http https
  ansible.posix.firewalld:
    zone: publicvps
    permanent: true
    service: "{{ item }}"
    state: enabled
  with_items:
    - http
    - https
  notify: reload firewalld

- name: Ensure admin zone allows http https
  ansible.posix.firewalld:
    zone: admin
    permanent: true
    service: "{{ item }}"
    state: enabled
  with_items:
    - http
    - https
  notify: reload firewalld
