---
# All entities that need to exist and reloaded in the runtime before further configuration is possible

- name: Ensure zones are present
  ansible.posix.firewalld:
    zone: "{{ item }}"
    permanent: true
    state: present
  loop: "{{ fw_zones_active }}"
  notify: reload firewalld

- name: Ensure ip sets are present
  ansible.builtin.template:
    src: "{{ item.template }}"
    dest: "{{ '/etc/firewalld/ipsets/' + item.dest }}"
    mode: 0644
  loop: "{{ fw_ipsets_active }}"
  notify: reload firewalld

- name: Ensure vpn service is present
  ansible.builtin.template:
    src: wireguard.xml.j2
    dest: "/etc/firewalld/services/wireguard.xml"
    mode: 0644
  when: firewalld_vpn_enabled
  notify:
    - reload firewalld
