---

- name: Ensure ip sets are bound
  ansible.posix.firewalld:
    zone: "{{ item.zone }}"
    permanent: true
    source: "{{ 'ipset:' + item.var.name }}"
    state: enabled
  when: item.var.use
  loop:
    - {zone: admin, var: "{{ firewalld_admin_ipset_ipfour }}"}
    - {zone: admin, var: "{{ firewalld_admin_ipset_ipsix }}"}
    - {zone: vps, var: "{{ firewalld_vps_ipset_ipfour }}"}
    - {zone: vps, var: "{{ firewalld_vps_ipset_ipsix }}"}
  notify: reload firewalld

- name: Ensure interfaces are bound
  ansible.posix.firewalld:
    zone: publicvps
    permanent: true
    interface: "{{ item.interface }}"
    state: enabled
  when: item.use
  loop:
    - {use: true, interface: "{{ ansible_default_ipv4['interface'] }}"}
    - {use: "{{ vps_ipv6_support }}", interface: "{{ ansible_default_ipv6['interface'] }}"}
  notify: reload firewalld
