---
- include_tasks: debian.yml

- name: Sysctl tuning
  ansible.posix.sysctl:
    name="{{ item.item }}"
    value="{{ item.value }}"
  when: item.item
  with_items:
    - "{{ sysctl|default([]) }}"
  tags:
    - always

- name: Force all notified handlers to run at this point, not waiting for normal sync points
  ansible.builtin.meta: flush_handlers
