---
# https://github.com/searxng/searxng-docker
# 'become' is determined at playbook level
# reload caddy:
# $ caddy_container_id=$(docker ps | grep caddy | awk '{print $1;}')
# $ docker exec -w /etc/caddy $caddy_container_id caddy reload

- name: Checkout searxng fork
  ansible.builtin.git:
    clone: true
    dest: "{{ searxng_install_dir }}"
    repo: "{{ searxng_git }}"
    version: master
    update: false
    force: false

# /run/user/1000/
- name: Retrieve the value of XDG_RUNTIME_DIR needed for templating
  ansible.builtin.shell: echo "$XDG_RUNTIME_DIR"
  changed_when: false
  args:
    executable: bash
  register: xdg_runtime_dir_result
  become: false

- name: Set fact XDG_RUNTIME_DIR
  ansible.builtin.set_fact:
    searxng_systemd_rootless_xdg_runtime_dir: "{{ xdg_runtime_dir_result.stdout }}"

# The service in the repo uses docker-compose,Should be docker compose
# Corrected based on searxng-docker.service.template
# The service file is directly put in systemd dir and does not exist in install dir
- name: Ensure service file is in systemd folder
  ansible.builtin.template:
    src: searxng-docker.service.j2
    dest: "{{ searxng_systemd_dir + '/searxng-docker.service' }}"
    mode: 0644

# TODO: This will be in /etc/caddy
- name: Ensure custom caddyfile is installed
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: "{{ searxng_install_dir + '/Caddyfile' }}"
    mode: 0644

- name: Ensure custom docker-compose file is installed
  ansible.builtin.template:
    src: docker-compose.yaml.j2
    dest: "{{ searxng_install_dir + '/docker-compose.yaml' }}"
    mode: 0644

- name: Ensure the settings are set
  ansible.builtin.template:
    src: settings.yml.j2
    dest: "{{ searxng_install_dir + '/searxng/settings.yml' }}"
    mode: 0644

- name: Searxng enabled and started
  ansible.builtin.systemd:
    name: searxng-docker
    enabled: true
    state: started
    scope: "{{ 'user' if searxng_rootless else 'system' }}"
