---

# https://github.com/searxng/searxng-docker
#
# TODO: docker compose non root user:
# https://docs.docker.com/engine/install/linux-postinstall

- name: Import configure searxng tasks
  ansible.builtin.import_tasks: configure.yml

- name: Searxng enabled
  ansible.builtin.systemd:
    name: /usr/local/searxng-docker/searxng-docker.service
    enabled: true

- name: Searxng started
  ansible.builtin.systemd:
    name: searxng-docker
    state: started
