---
# https://github.com/searxng/searxng-docker
# --> 'become' is determined at playbook level <--
#
# Deviations from the install method described on searxng-docker website:
# no .env file necessary, custom docker compose without caddy, custom Caddyfile
# searxng-docker.service is put directly into the systemd dir
# searxng-docker.service is modified: docker compose instead of docker-compose
# searxng-docker.service is modified: DOCKER_HOST when rootless
# Caddyfile can block ips

- name: Checkout searxng fork
  ansible.builtin.git:
    clone: true
    dest: "{{ searxng_install_dir }}"
    repo: "{{ searxng_git }}"
    version: master
    update: false
    force: false

# /run/user/1000/
- name: Retrieve the value of XDG_RUNTIME_DIR needed for templating systemd service
  ansible.builtin.shell: echo "$XDG_RUNTIME_DIR"
  changed_when: false
  args:
    executable: bash
  register: xdg_runtime_dir_result

- name: Set fact XDG_RUNTIME_DIR
  ansible.builtin.set_fact:
    searxng_systemd_rootless_xdg_runtime_dir: "{{ xdg_runtime_dir_result.stdout }}"

- name: Ensure service file is in systemd folder
  ansible.builtin.template:
    src: searxng-docker.service.j2
    dest: "{{ searxng_systemd_dir + '/searxng-docker.service' }}"
    mode: 0644

- name: Ensure custom caddyfile is installed in /etc/caddy
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: /etc/caddy/Caddyfile
    backup: true
    mode: 0644
  become: true
  notify: restart caddy

- name: Ensure custom docker-compose file is installed
  ansible.builtin.template:
    src: docker-compose.yaml.j2
    dest: "{{ searxng_install_dir + '/docker-compose.yaml' }}"
    mode: 0644

- name: Ensure the settings are set
  ansible.builtin.template:
    src: settings.yml.j2
    dest: "{{ searxng_install_dir + '/searxng/settings.yml' }}"
    mode: 0644
  notify:
    - restart searxng

- name: Searxng enabled and started
  ansible.builtin.systemd:
    name: searxng-docker
    enabled: true
    state: started
    scope: "{{ 'user' if searxng_rootless else 'system' }}"
