---
# https://github.com/searxng/searxng-docker
# --> 'become' is determined at playbook level <--
#
# Deviations from the install method described on searxng-docker website:
# no .env file necessary, custom docker compose without caddy, custom Caddyfile
# searxng-docker.service is put directly into the systemd dir
# searxng-docker.service is modified: docker compose instead of docker-compose
# Caddyfile can block ips
#
# rootless: no service file, uses docker compose with restart: unless-stopped

- name: Checkout searxng fork
  ansible.builtin.git:
    clone: true
    dest: "{{ searxng_install_dir }}"
    repo: "{{ searxng_git }}"
    version: master
    update: false
    force: false

- name: Searxng tasks
  ansible.builtin.import_tasks: searxng.yml
  when: not searxng_rootless

- name: Searxng rootless installation tasks
  ansible.builtin.import_tasks: searxng-rootless.yml
  when: searxng_rootless
