---

- name: Ensure custom caddyfile is installed in /etc/caddy
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: /etc/caddy/Caddyfile
    backup: true
    mode: 0644
  become: true
  notify: restart caddy

- name: Ensure custom docker-compose file is installed
  ansible.builtin.template:
    src: docker-compose.yaml.j2
    dest: "{{ searxng_install_dir + '/docker-compose.yaml' }}"
    mode: 0644

- name: Ensure the settings are set
  ansible.builtin.template:
    src: settings.yml.j2
    dest: "{{ searxng_install_dir + '/searxng/settings.yml' }}"
    mode: 0644
  notify:
    - restart rootless searxng

# beware of non-zero return code...
- name: Capture if searxng is running
  ansible.builtin.shell: |
    set -o pipefail && \
    export DOCKER_HOST=unix://$XDG_RUNTIME_DIR/docker.sock && \
    docker ps | grep -c searxng || true
  args:
    chdir: "{{ searxng_install_dir }}"
    executable: /bin/bash
  register: searxng_running
  changed_when: false

- name: Ensure searxng is running
  ansible.builtin.shell: |
    export DOCKER_HOST=unix://$XDG_RUNTIME_DIR/docker.sock && \
    docker compose up -d
  args:
    chdir: "{{ searxng_install_dir }}"
    executable: /bin/bash
  when: searxng_running.stdout == '0'
