---
- name: restart firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: restarted
    daemon_reload: true

- name: reload firewalld
  ansible.builtin.command:
    cmd: firewall-cmd --reload
