---

- name: Software tasks
  ansible.builtin.import_tasks: software-prerequisites.yml

- name: Additional rootless software tasks
  ansible.builtin.import_tasks: rootless-software-prerequisites.yml

- name: Rootless tasks before installation
  ansible.builtin.import_tasks: rootless-config.yml
  become: false

- name: Ensure rootless settings
  ansible.builtin.import_tasks: rootless-settings.yml

- name: Set fact run_setuptool
  ansible.builtin.import_tasks: rootless-setuptool-fact.yml

# on digital ocean, debian comes with a .profile and a .bashrc
# /home/<user>/bin is added in .profile file which is not seen by ansible over ssh
# add variables to the top of .bashrc before it bails out when terminal is not interactive
- name: Ensure .bash_profile contains DOCKER_HOST export and bin path
  ansible.builtin.lineinfile:
    dest: "{{ item.dest }}"
    line: "{{ item.line }}"
    state: present
    backup: true
    insertbefore: BOF
  with_items:
    - {line: 'export DOCKER_HOST=unix://$XDG_RUNTIME_DIR/docker.sock', dest: '~/.bashrc'}
    - {line: 'export PATH=$HOME/bin:$PATH', dest: '~/.bashrc'}
  become: false

- name: Ensure .zshenv contains DOCKER_HOST export and bin path
  ansible.builtin.lineinfile:
    dest: "{{ item.dest }}"
    line: "{{ item.line }}"
    state: present
    backup: true
  with_items:
    - {line: 'export DOCKER_HOST=unix://$XDG_RUNTIME_DIR/docker.sock', dest: '~/.config/zsh/.zshenv'}
    - {line: 'export PATH=$HOME/bin:$PATH', dest: '~/.config/zsh/.zshenv'}
  when: docker_rootless_and_terminal_software_zsh_enabled
  become: false

- name: Ensure script dockerd-rootless-setuptool runs
  ansible.builtin.shell: |
    set -o pipefail && \
    curl -fsSL https://get.docker.com/rootless | sh
  args:
    executable: /bin/bash
  changed_when: false
  become: false
  when: run_setuptool

- name: Ensure docker compose folder exists
  ansible.builtin.file:
    state: directory
    path: "$HOME/.docker/cli-plugins"
    mode: 0755
  become: false
  when: run_setuptool

- name: Ensure script for docker compose runs
  ansible.builtin.shell: |
    curl -SL https://github.com/docker/compose/releases/download/v2.6.0/docker-compose-linux-x86_64 \
    -o $HOME/.docker/cli-plugins/docker-compose && \
    chmod +x $HOME/.docker/cli-plugins/docker-compose
  args:
    warn: false
    executable: /bin/bash
    creates: "$HOME/.docker/cli-plugins/docker-compose"
  become: false
  when: run_setuptool

- name: Ensure reboot after rootless setup script has ran.
  ansible.builtin.reboot:
  when: run_setuptool

- name: Wait until the server becomes ready...
  ansible.builtin.wait_for_connection:
    delay: 20
    timeout: 320
  when: run_setuptool

# TODO Fails on first run!
# # The socket path is set to $XDG_RUNTIME_DIR/docker.sock by default. $XDG_RUNTIME_DIR is typically set to /run/user/$UID.
# # The data dir is set to ~/.local/share/docker by default. The data dir should not be on NFS.
# # The daemon config dir is set to ~/.config/docker by default. This directory is different from ~/.docker that is used by the client.
- name: Ensure rootless docker is enabled and started
  ansible.builtin.systemd:
    service: docker
    scope: user
    state: started
    enabled: true
  become: false
