---
# Systemwide caddy uses volumes:
# "Name": "searxng-docker_caddy-data",
#                 "Source": "/var/lib/docker/volumes/searxng-docker_caddy-data/_data",
# "Name": "searxng-docker_caddy-config",
#                "Source": "/var/lib/docker/volumes/searxng-docker_caddy-config/_data",
# docker volume create bla, rootless:
# Mountpoint": "/home/user/.local/share/docker/volumes/bla/_data
#
# This folder contains the certificates, owned by root:
# /var/lib/docker/volumes/searxng-docker_caddy-data/_data/caddy

# Add directory before installing docker so no restart is required
- name: Ensure rootless config docker directory is present
  ansible.builtin.file:
    path: ~/.config/docker
    state: directory
    mode: 0755

# Mode: 0644 or more restrictive
# Not present by default after docker installed
# Configure default logging driver https://docs.docker.com/engine/install/linux-postinstall/
- name: Ensure rootless daemon.json is present
  ansible.builtin.copy:
    src: daemon.json
    dest: ~/.config/docker
    mode: 0600
