---

- name: Software tasks
  ansible.builtin.import_tasks: software.yml

- name: Repo tasks
  ansible.builtin.import_tasks: repo.yml

- name: Additional rootless software tasks
  ansible.builtin.import_tasks: software-rootless-additional.yml
  when: rootless_docker_enabled

- name: Systemwide tasks before installation
  ansible.builtin.import_tasks: install-systemwide-pre.yml
  when: not rootless_docker_enabled

- name: Rootless tasks before installation
  ansible.builtin.import_tasks: install-rootless-pre.yml
  when: rootless_docker_enabled
  become: false

- name: Install tasks
  ansible.builtin.import_tasks: install.yml

- name: Rootless tasks after installation
  ansible.builtin.import_tasks: install-rootless-post.yml
  when: rootless_docker_enabled

# notify: reset connection
- name: Ensure user is added to the docker group
  ansible.builtin.user:
    name: "{{ vps_user }}"
    append: true
    groups: docker
