---

- name: Software tasks
  ansible.builtin.import_tasks: software.yml

- name: Repo tasks
  ansible.builtin.import_tasks: repo.yml

- name: Additional rootless software tasks
  ansible.builtin.import_tasks: software-rootless-additional.yml
  when: docker_rootless_enabled

- name: Systemwide tasks before installation
  ansible.builtin.import_tasks: install-systemwide-pre.yml
  when: not docker_rootless_enabled

- name: Rootless tasks before installation
  ansible.builtin.import_tasks: install-rootless-pre.yml
  when: docker_rootless_enabled
  become: false

# 20.10.16
# TODO: 20.10.17 rootless docker on restart no more containers searxn proces dead
- name: Install tasks
  ansible.builtin.import_tasks: install.yml

# notify: reset connection
- name: Ensure user is added to the docker group
  ansible.builtin.user:
    name: "{{ vps_user }}"
    append: true
    groups: docker

- name: Rootless tasks after installation
  ansible.builtin.import_tasks: install-rootless-post.yml
  when: docker_rootless_enabled
