---

- name: Import software tasks
  ansible.builtin.import_tasks: software.yml

- name: Import rootless software tasks
  ansible.builtin.import_tasks: rootless-software.yml
  when: rootless_docker_enabled

- name: Import repo tasks
  ansible.builtin.import_tasks: repo.yml

- name: Import install tasks
  ansible.builtin.import_tasks: install.yml

- name: Import rootless additional tasks
  ansible.builtin.import_tasks: rootless.yml
  when: rootless_docker_enabled

- name: Ensure user is added to the docker group
  ansible.builtin.user:
    name: "{{ vps_user }}"
    append: true
    groups: docker

# When in terminal one would use: newgrp docker
- name: reset ssh connection to allow user changes to affect ansible user
  ansible.builtin.meta:
    reset_connection
