---

# curl -fsSL https://get.docker.com/rootless | sh
# https://download.docker.com/linux/debian/dists/bullseye/pool/stable/amd64/
# https://docs.docker.com/compose/install/compose-plugin/#install-the-plugin-manually
# rootless docker with systemd: does not start on reboot. Use docker compose directly

- name: Docker tasks
  ansible.builtin.import_tasks: docker.yml
  when: true
