---

- name: Docker tasks
  ansible.builtin.import_tasks: docker.yml
  when: not docker_rootless_enabled

- name: Rootless Docker tasks
  ansible.builtin.import_tasks: docker-rootless-added.yml
  when: docker_rootless_enabled
