---

# https://www.linuxuprising.com/2021/01/apt-key-is-deprecated-how-to-add.html
- name: Ensure docker key is trusted
  ansible.builtin.shell:
    set -o pipefail && \
    curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor \
    -o /usr/share/keyrings/docker-archive-keyring.gpg
  args:
    warn: false
    creates: "/usr/share/keyrings/docker-archive-keyring.gpg"
    executable: /bin/bash

- name: Retrieve deb architecture
  ansible.builtin.command: dpkg --print-architecture
  changed_when: false
  register: deb_architecture

- name: Ensure docker repository is enabled
  ansible.builtin.apt_repository:
    filename: docker
    repo: "deb [arch={{ deb_architecture.stdout }} signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"
    state: present
    update_cache: true
