---

# https://docs.docker.com/engine/security/rootless/

# rootless mode:
# dbus-user-session, already present
- name: Ensure APT usage dependencies for rootless are installed
  ansible.builtin.apt:
    name:
      - uidmap
      - dbus-user-session
      - fuse-overlayfs
      - rootlesskit
    state: present
    update_cache: true
