---

- name: Capture if dockerd-rootless-setuptool needs running
  ansible.builtin.stat:
    path: ~/.config/systemd/user/docker.service
  register: run_dockerd_rootless_setuptool_required
  become: false

- name: Set fact dockerd-rootless-setuptool needs running
  ansible.builtin.set_fact:
    run_setuptool: "{{ not run_dockerd_rootless_setuptool_required.stat.exists }}"
  become: false
