---

# https://docs.docker.com/engine/install/debian/#prerequisites
#
# ntp: on debian chrony is installed
# lsb-release: The Linux Standard Base (http://www.linuxbase.org/) is a standard core system
# that third-party applications written for Linux can depend upon.
- name: Ensure APT usage dependencies are installed
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - gnupg
      - curl
      - lsb-release
    state: present
    update_cache: true
