---

- name: Set ip_subject_alt_name as a fact
  ansible.builtin.set_fact:
    ip_subject_alt_name: "{{ ansible_default_ipv4.address }}"
- name: Set IPv6 support as a fact
  ansible.builtin.set_fact:
    ipv6_support: "{% if ansible_default_ipv6['gateway'] is defined %}true{% else %}false{% endif %}"
