---

- name: restart caddy
  ansible.builtin.systemd:
    name: caddy
    state: restarted
  become: true

- name: restart searxng
  ansible.builtin.systemd:
    name: searxng-docker
    state: restarted
    scope: "{{ 'user' if searxng_rootless else 'system' }}"
