---

- name: restart caddy
  ansible.builtin.systemd:
    name: caddy
    state: restarted
  become: true

- name: restart searxng
  ansible.builtin.systemd:
    name: searxng-docker
    state: restarted

- name: restart rootless searxng
  ansible.builtin.shell: |
    export DOCKER_HOST=unix://$XDG_RUNTIME_DIR/docker.sock && \
    docker compose restart
  args:
    chdir: "{{ searxng_install_dir }}"
    executable: /bin/bash
