---

# sudo systemctl status unattended-upgrades
# usr/share/unattended-upgrades/unattended-upgrade-shutdown --wait-for-signal
- name: Import unattended upgrades tasks
  ansible.builtin.import_tasks: unattended-upgrades.yml

# First configure unattended upgrades because sometimes the following occurs:
# '/usr/bin/apt-get dist-upgrade ' failed: E: Could not get lock /var/lib/dpkg/lock-frontend. It is held by process 853 (unattended-upgr)
- name: Import software upgrades tasks
  ansible.builtin.import_tasks: software-upgrades.yml
  tags:
    - upgrade-all

- name: Disable MOTD on login and SSHD
  ansible.builtin.replace: dest="{{ item.file }}" regexp="{{ item.regexp }}" replace="{{ item.line }}"
  with_items:
    - {regexp: '^session.*optional.*pam_motd.so.*', line: '# MOTD DISABLED', file: '/etc/pam.d/login'}
    - {regexp: '^session.*optional.*pam_motd.so.*', line: '# MOTD DISABLED', file: '/etc/pam.d/sshd'}

- name: Ensure sysctl is tuned
  ansible.posix.sysctl:
    name="{{ item.item }}"
    value="{{ item.value }}"
  when: item.item
  with_items:
    - item: net.ipv4.ip_forward
      value: 1
    - item: net.ipv4.conf.all.forwarding
      value: 1
    - item: "{{ 'net.ipv6.conf.all.forwarding' if vps_ipv6_support else none }}"
      value: 1

- name: Ensure systemd services enabled and started
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: true
    daemon_reload: true
  with_items:
    - systemd-networkd
    - systemd-resolved
    - unattended-upgrades

- name: Import software tasks
  ansible.builtin.import_tasks: software.yml
