---

- name: Import software upgrades tasks
  ansible.builtin.import_tasks: software-upgrades.yml
  tags:
    - setup-all
    - upgrade-all

- name: Import unattended upgrades tasks
  ansible.builtin.import_tasks: unattended-upgrades.yml
  tags:
    - setup-all

- name: Import infrastructure tasks
  ansible.builtin.import_tasks: infra.yml
  tags:
    - setup-all

- name: Ensure systemd services enabled and started
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: true
    daemon_reload: true
  with_items:
    - systemd-networkd
    - systemd-resolved
    - unattended-upgrades
  tags:
    - always

- name: Force all notified handlers to run at this point, not waiting for normal sync points
  ansible.builtin.meta: flush_handlers
  tags:
    - always

- name: Import facts tasks
  ansible.builtin.import_tasks: facts.yml
  tags:
    - always

- name: Import software tasks
  ansible.builtin.import_tasks: software.yml
  tags:
    - setup-all

- name: Ensure sysctl is tuned
  ansible.posix.sysctl:
    name="{{ item.item }}"
    value="{{ item.value }}"
  when: item.item
  with_items:
    - item: net.ipv4.ip_forward
      value: 1
    - item: net.ipv4.conf.all.forwarding
      value: 1
    - item: "{{ 'net.ipv6.conf.all.forwarding' if ipv6_support else none }}"
      value: 1
  tags:
    - setup-all

- name: Force all notified handlers to run at this point, not waiting for normal sync points
  ansible.builtin.meta: flush_handlers
  tags:
    - always
