---

- name: New wg host, generate keys
  ansible.builtin.shell: vps_wg_host_keys
  register: wg_hostkeys
  changed_when: false
  args:
    executable: bash

- name: Fact, add host information to internal dictionary
  ansible.builtin.set_fact:
    wg_host: "{{ wg_host | default({}) | combine(\
                { 'ip': ip, 'ipv6': ipv6, 'port': port, 'key': key, 'pubkey': pubkey }) }}"
  vars:
    ip: "{{ wireguard_network_ipv4 | ansible.utils.ipaddr('1') }}"
    ipv6: "{{ wireguard_network_ipv6 | ansible.utils.ipaddr('1') if vps_ipv6_support else '' }}"
    port: "{{ wireguard_port }}"
    key: "{{ wg_hostkeys.stdout_lines[0] }}"
    pubkey: "{{ wg_hostkeys.stdout_lines[1] }}"
  no_log: "{{ wireguard_no_log }}"

- name: Create host interface file
  ansible.builtin.template:
    src: host_interface.conf.j2
    dest: "{{ wg_part_host }}"
    mode: "0600"
