---

- name: Copy existing host file to wg_part_host
  ansible.builtin.copy:
    src: "{{ wireguard_host_conf }}"
    dest: "{{ wg_part_host }}"
    remote_src: true
    mode: 0600

- name: Remove all blocks from existing peers not present in user configuration
  ansible.builtin.blockinfile:
    path: "{{ wg_part_host }}"
    marker_begin: "--> {{ item }} <--"
    marker_end: "{{ item }} END"
    block: ''
  loop: "{{ wg_peers_to_delete }}"

- name: Ip adminstration, register deleted peer action
  ansible.builtin.shell: |
    for i in {1..{{ wg_peers_to_delete | length }}}
    do
      echo "# Peer REMOVED ANSIBLE MANAGED" >> {{ wg_part_host }}
    done
  when: wg_peers_to_delete | length > 0
  args:
    executable: bash

