---
- name: Ensure zones drop ssh
  ansible.posix.firewalld:
    zone: "{{ item }}"
    permanent: true
    rich_rule: 'rule priority=1 service name="ssh" drop'
    state: enabled
  notify: reload firewalld
