---
# on debian: mkpasswd --method=SHA-512
# override ansible_ssh_user in invoking shellscript
# Note: algo does ipv6: true
- hosts: wgvps_servers
  gather_facts: false
  vars:
    - drb_password: '$6$4AJcweVG$ww2ta9FD8ULuGIzgdWBkXiFr4yfQjFzd0HI9mXl4RxVtobcsrdqa.5KsPfC4PXGDdbddCVdLRev2MOjwGYwca0'

  # ansible webserver -m ping
  # ansible webserver -m shell -a id
  # protect ssh
  # add drb user as sudo
  tasks:

    - name: Add a new user
      ansible.builtin.user:
        name: ajb
        password: "{{ drb_password }}"
        append: true
        # groups: adm, netdev
        groups: sudo
        update_password: on_create
        shell: /bin/bash

    - name: add SSH Key to authorized
      ansible.posix.authorized_key:
        user: ajb
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/laptop2drieberen.pub') }}"
        state: present

    # For state=present, the pattern to replace if found. Only the last line found will be replaced.
    # If the regular expression is not matched, the line will be added to the file in keeping with insertbefore or insertafter settings.
    - name: Ensure no password Authentication
      ansible.builtin.lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: "PasswordAuthentication no"
        state: present
        backup: true
      notify:
        - restart ssh

    - name: Ensure no root Login
      ansible.builtin.lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: "PermitRootLogin no"
        state: present
        backup: true
      notify:
        - restart ssh

    # - name: Ensure SSH only ip4
    #   ansible.builtin.lineinfile:
    #     dest: /etc/ssh/sshd_config
    #     regexp: '^AddressFamily'
    #     line: "AddressFamily inet"
    #     state: present
    #     backup: true
    #   notify:
    #     - restart ssh

    - name: Ensure no SSH ChallengeResponseAuthentication
      ansible.builtin.lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^ChallengeResponseAuthentication'
        line: "ChallengeResponseAuthentication no"
        state: present
        backup: true
      notify:
        - restart ssh

  handlers:
    - name: restart ssh
      ansible.builtin.service:
        name: sshd
        state: restarted
