---

searxng_enabled: false
#
searxng_rootless: false
#
# Restrict access to home ip and wireguard:
searxng_public: false
#
searxng_hostname: ''
searxng_email: ''
#
# The url to the git repository:
searxng_git: https://github.com/searxng/searxng-docker.git

# openssl rand -hex 32
searxng_secret_key: VERYSECRET
#
# Install dir, working dir in service file
searxng_install_dir_systemwide: "/usr/local/searxng-docker"
searxng_install_dir_rootless: "{{ '/home/' + vps_user + '/builds/searxng-docker' }}"
#
# Service dir
searxng_systemd_dir_systemwide: "/etc/systemd/system"
searxng_systemd_dir_rootless: "{{ '/home/' + vps_user + '/.config/systemd/user' }}"

# Rootless: path containing docker sock
searxng_systemd_rootless_xdg_runtime_dir: ''

# Note: This assignment defaulting to self triggers an ansible exception:
# searxng_install_dir: "{{ searxng_install_dir_rootless if docker_rootless_enabled else searxng_install_dir }}"
#
# Defaults to systemwide:
searxng_install_dir: "{{ searxng_install_dir_systemwide }}"
searxng_systemd_dir: "{{ searxng_systemd_dir_systemwide }}"
