---
###############################################################################
# Modifiable:
searxng_enabled: true
#
searxng_hostname: ''
searxng_email: ''
#
# openssl rand -hex 32
searxng_secret_key: "ultrasecretkey"  # change this!
#
# Restrict access to home ip and wireguard:
searxng_public: false
# The url to the git repository:
searxng_git: https://github.com/searxng/searxng-docker.git

###############################################################################
# Tweaking:
searxng_default_lang: 'en-US'

# Limit the number of engines by adding engines to this restrict list
# Default behaviour: remove the specified engines if list has items
# The keep option keeps the specified engines and remove all others
searxng_engines_restrict: []
searxng_engines_restrict_keep: false

###############################################################################
# Path configuration, modify with care, should not be needed
# Install dir, working dir in service file
searxng_install_dir_systemwide: "/usr/local/searxng-docker"
searxng_install_dir_rootless: "{{ '/home/' + vps_user + '/builds/searxng-docker' }}"
#
# Service dir
searxng_systemd_dir_systemwide: "/etc/systemd/system"
searxng_systemd_dir_rootless: "{{ '/home/' + vps_user + '/.config/systemd/user' }}"

# Defaults to systemwide:
searxng_install_dir: "{{ searxng_install_dir_systemwide }}"
searxng_systemd_dir: "{{ searxng_systemd_dir_systemwide }}"

###############################################################################
# Not modifiable:
#
# see groupvars:
searxng_rootless: false
