---

- name: Ensure parts directory on host exists
  ansible.builtin.file:
    dest: "{{ wireguard_parts_path }}"
    state: directory
    mode: 0700

- name: Ensure wireguard folder on ansible controller exists
  ansible.builtin.file:
    dest: "{{ wireguard_config_path }}/deleted"
    state: directory
    recurse: true
  delegate_to: localhost
  become: false
