---

# Make sure the configured wireguard_users are unique
- name: Facts as base for all further role processing
  ansible.builtin.set_fact:
    wg_peers_given: "{{ wireguard_users | default([]) | unique }}"
    wg_modify: false
    wg_new_host: false
    wg_peers_from_host: []
    wg_peers_to_delete: []
    wg_peers_to_add: []

- name: Facts, hosts config file
  ansible.builtin.stat:
    path: "{{ '/etc/wireguard/' + wireguard_interface + '.conf' }}"
  register: wireguard_host_result
- name: Facts, set wg_new_host
  ansible.builtin.set_fact:
    wg_new_host: "{{ not wireguard_host_result.stat.exists }}"

- name: Facts, new host
  ansible.builtin.include_tasks: modify/facts_new.yml
  when: wg_new_host

- name: Facts, existing host
  ansible.builtin.include_tasks: modify/facts_existing.yml
  when: not wg_new_host

- name: Fact, calculate reduce_mtu
  ansible.builtin.set_fact:
    wireguard_reduce_mtu: >
      "{{
      1500 - ansible_default_ipv4['mtu'] | int
      if wireguard_reduce_mtu | int == 0 and ansible_default_ipv4['mtu'] | int < 1500
      else wireguard_reduce_mtu | int
      }}"

- name: Show facts as base for all further role processing
  ansible.builtin.debug:
    msg: |
      wg_peers_given: {{ wg_peers_given }}
      modify: {{ wg_modify }}
      new_host: {{ wg_new_host }}
      reduce_mtu: {{ wireguard_reduce_mtu }}
      wireguard_peers_ip_index_start: {{ wireguard_peers_ip_index_start }}
      from_host: {{ wg_peers_from_host }}
      to_delete: {{ wg_peers_to_delete }}
      to_add: {{ wg_peers_to_add }}
