---

- name: Facts, to delete, to add, new config
  ansible.builtin.set_fact:
    wg_to_delete: []
    wg_to_add: []
    wg_new_server: false

- name: Facts, test if server has a .conf file
  ansible.builtin.stat:
    path: "{{ '/etc/wireguard/' + wireguard_interface + '.conf' }}"
  register: wireguard_server_conf_result

- name: Facts, when no conf file on server, build new
  ansible.builtin.set_fact:
    wg_new_server: "{{ _result }}"
    wg_to_add: "{{ wireguard_users if _result else [] }}"
  vars:
    _result: "{{ not wireguard_server_conf_result.stat.exists }}"

- name: Facts, when existing conf file on server, build existing
  ansible.builtin.set_fact:
    wg_to_add: [phone3]
  when: not wg_new_server

# - name: Ensure no local wireguard config present on new wg creation
#   ansible.builtin.file:
#     dest: "{{ wireguard_config_path }}"
#     state: absent
#   delegate_to: localhost
#   become: false

# - name: Add or delete block
#   block:
#     - name: Facts add or delete
#       ansible.builtin.set_fact:
#         wg_to_delete: [phone]
#         wg_to_add: [newphone]
#   when: not wg_new_server
