---

# Tested, at first glance: no speed benefit when connecting to host over ipv6...
# - "{{ [wg_client.name + '_ipv6','client_over_ipv6.conf.j2']  if wireguard_client_generate_extra_ipv6 else omit }}"
- name: Client config block
  block:
    - name: Ensure client config generated
      ansible.builtin.template:
        src: "{{ item.1 }}"
        dest: "{{ wireguard_config_path }}/{{ item.0 }}.conf"
        mode: "0600"
      loop:
        - "{{ [wg_client.name,'client.conf.j2'] }}"

    # disable ansible lint var spacing because of || true in script
    - name: Ensure QR codes generated  # noqa var-spacing
      ansible.builtin.shell: >
        umask 077;
        which segno &&
        segno --scale=5 --output={{ item.0 }}.png \
          "{{ lookup('template', item.1) }}" || true
      changed_when: false
      vars:
        ansible_python_interpreter: "{{ ansible_playbook_python }}"
      args:
        chdir: "{{ wireguard_config_path }}"
        executable: bash
      loop:
        - "{{ [wg_client.name,'client.conf.j2'] }}"
  delegate_to: localhost
  become: false
