---

- name: Client config block
  block:
    - name: Ensure client config generated
      ansible.builtin.template:
        src: client.conf.j2
        dest: "{{ wireguard_config_path }}/{{ wg_client.name }}.conf"
        mode: "0600"

    # disable ansible lint var spacing because of || true in script
    - name: Ensure QR codes generated  # noqa var-spacing
      ansible.builtin.shell: >
        umask 077;
        which segno &&
        segno --scale=5 --output={{ wg_client.name }}.png \
          "{{ lookup('template', 'client.conf.j2') }}" || true
      changed_when: false
      vars:
        ansible_python_interpreter: "{{ ansible_playbook_python }}"
      args:
        chdir: "{{ wireguard_config_path }}"
        executable: bash
  delegate_to: localhost
  become: false
