---

# the lock files on the server are "done" markers, never containing content

# only generates a new key when there is no corresponding lock file on the server
- name: Generate private keys
  ansible.builtin.command: wg genkey
  register: wg_genkey
  args:
    creates: "/etc/wireguard/private_{{ item }}.lock"
  with_items:
    - "{{ wireguard_users }}"
    - "{{ wireguard_host_ip }}"
  notify:
    - Save private keys
    - Touch private lock files

- name: Generate preshared keys
  ansible.builtin.command: wg genpsk
  register: wg_genpsk
  args:
    creates: "/etc/wireguard/preshared_{{ item }}.lock"
  with_items:
    - "{{ wireguard_users }}"
    - "{{ wireguard_host_ip }}"
  notify:
    - Save preshared keys
    - Touch preshared lock files

- name: Force all notified handlers to run at this point, not waiting for normal sync points
  ansible.builtin.meta: flush_handlers

# public keys are derived from private keys
- name: Generate public keys
  ansible.builtin.shell: |
    set -o pipefail
    echo "{{ lookup('file', wireguard_pki_path + '/private/' + item) }}" |
    wg pubkey
  register: wg_pubkey
  changed_when: false
  args:
    executable: bash
  with_items:
    - "{{ wireguard_users }}"
    - "{{ wireguard_host_ip }}"

- name: Save public keys
  ansible.builtin.copy:
    dest: "{{ wireguard_pki_path }}/public/{{ item['item'] }}"
    content: "{{ item['stdout'] }}"
    mode: "0600"
  no_log: "{{ wireguard_no_log | bool }}"
  with_items: "{{ wg_pubkey['results'] }}"
  delegate_to: localhost
  become: false
