---

# the lock files on the server are "done" markers, never containing content
- name: Delete the lock files when always generating new keys
  ansible.builtin.file:
    dest: "{{ config_prefix|default('/') }}etc/wireguard/private_{{ item }}.lock"
    state: absent
  when: not wireguard_pki_keep_future_user_add_ability|bool
  with_items:
    - "{{ wireguard_users }}"
    - "{{ ip_subject_alt_name }}"

# only generates a new key when there is no corresponding lock file on the server
- name: Generate private keys
  ansible.builtin.command: wg genkey
  register: wg_genkey
  args:
    creates: "{{ config_prefix|default('/') }}etc/wireguard/private_{{ item }}.lock"
  with_items:
    - "{{ wireguard_users }}"
    - "{{ ip_subject_alt_name }}"

# on change, copy changed server stdout result to a file on the ansible controller
# then, on server, create a new lock file
- block:
    # notice the content being "stdout"...
    - name: Save private keys
      ansible.builtin.copy:
        dest: "{{ wireguard_pki_path }}/private/{{ item['item'] }}"
        content: "{{ item['stdout'] }}"
        mode: "0600"
      no_log: "{{ no_log|bool }}"
      when: item.changed
      with_items: "{{ wg_genkey['results'] }}"
      delegate_to: localhost
      become: false

    - name: Touch the lock file
      ansible.builtin.file:
        dest: "{{ config_prefix|default('/') }}etc/wireguard/private_{{ item }}.lock"
        state: touch
        mode: "0644"
      with_items:
        - "{{ wireguard_users }}"
        - "{{ ip_subject_alt_name }}"
  when: wg_genkey.changed

- name: Delete the preshared lock files
  ansible.builtin.file:
    dest: "{{ config_prefix|default('/') }}etc/wireguard/preshared_{{ item }}.lock"
    state: absent
  when: not wireguard_pki_keep_future_user_add_ability|bool
  with_items:
    - "{{ wireguard_users }}"
    - "{{ ip_subject_alt_name }}"

- name: Generate preshared keys
  ansible.builtin.command: wg genpsk
  register: wg_genpsk
  args:
    creates: "{{ config_prefix|default('/') }}etc/wireguard/preshared_{{ item }}.lock"
  with_items:
    - "{{ wireguard_users }}"
    - "{{ ip_subject_alt_name }}"

- block:
    - name: Save preshared keys
      ansible.builtin.copy:
        dest: "{{ wireguard_pki_path }}/preshared/{{ item['item'] }}"
        content: "{{ item['stdout'] }}"
        mode: "0600"
      no_log: "{{ no_log|bool }}"
      when: item.changed
      with_items: "{{ wg_genpsk['results'] }}"
      delegate_to: localhost
      become: false

    - name: Touch the preshared lock file
      ansible.builtin.file:
        dest: "{{ config_prefix|default('/') }}etc/wireguard/preshared_{{ item }}.lock"
        state: touch
        mode: 0644
      with_items:
        - "{{ wireguard_users }}"
        - "{{ ip_subject_alt_name }}"
  when: wg_genpsk.changed

# public keys are derived from private keys
- name: Generate public keys
  ansible.builtin.shell: |
    set -o pipefail
    echo "{{ lookup('file', wireguard_pki_path + '/private/' + item) }}" |
    wg pubkey
  register: wg_pubkey
  changed_when: false
  args:
    executable: bash
  with_items:
    - "{{ wireguard_users }}"
    - "{{ ip_subject_alt_name }}"

- name: Save public keys
  ansible.builtin.copy:
    dest: "{{ wireguard_pki_path }}/public/{{ item['item'] }}"
    content: "{{ item['stdout'] }}"
    mode: "0600"
  no_log: "{{ no_log|bool }}"
  with_items: "{{ wg_pubkey['results'] }}"
  delegate_to: localhost
  become: false
