---
- name: Ensure the required directories exist
  ansible.builtin.file:
    dest: "{{ item }}"
    state: directory
    recurse: true
  with_items:
    - "{{ wireguard_pki_path }}/preshared"
    - "{{ wireguard_pki_path }}/private"
    - "{{ wireguard_pki_path }}/public"
  delegate_to: localhost
  become: false

- name: Calculate reduce_mtu as a fact
  ansible.builtin.set_fact:
    reduce_mtu: "{{ 1500 - ansible_default_ipv4['mtu']|int if reduce_mtu|int == 0 and ansible_default_ipv4['mtu']|int < 1500 else reduce_mtu|int }}"

- name: Ensure wireguard installed
  ansible.builtin.apt:
    name: wireguard
    state: present
    update_cache: true

- name: Import keygeneration tasks
  ansible.builtin.import_tasks: keys.yml
  tags:
    - update-users

- name: Import configuration tasks
  ansible.builtin.import_tasks: config.yml
  tags:
    - update-users

- name: WireGuard enabled and started
  ansible.builtin.systemd:
    name: "{{ wireguard_service_name }}"
    state: started
    enabled: true

- name: Delete the PKI directory
  ansible.builtin.file:
    path: "{{ wireguard_pki_path }}"
    state: absent
  become: false
  delegate_to: localhost
  when:
    - not store_pki
    - not pki_in_tmpfs

- name: Force all notified handlers to run at this point, not waiting for normal sync points
  ansible.builtin.meta: flush_handlers
