---
- name: Ensure setting wireguard_pki_keep_future_user_add_ability, no old local keys on start
  ansible.builtin.import_tasks: pki_on_disk.yml

- name: Ensure the required directories exist
  ansible.builtin.file:
    dest: "{{ item }}"
    state: directory
    recurse: true
  with_items:
    - "{{ wireguard_pki_path }}/preshared"
    - "{{ wireguard_pki_path }}/private"
    - "{{ wireguard_pki_path }}/public"
  delegate_to: localhost
  become: false

- name: Calculate reduce_mtu as a fact
  ansible.builtin.set_fact:
    wireguard_reduce_mtu: >
      "{{
      1500 - ansible_default_ipv4['mtu']|int
      if wireguard_reduce_mtu|int == 0 and ansible_default_ipv4['mtu']|int < 1500
      else wireguard_reduce_mtu|int
      }}"

- name: Ensure wireguard installed
  ansible.builtin.apt:
    name: wireguard
    state: present
    update_cache: true

- name: Import keygeneration tasks
  ansible.builtin.import_tasks: keys.yml

- name: Import config generation tasks
  ansible.builtin.import_tasks: config.yml

- name: Force all notified handlers to run at this point, not waiting for normal sync points
  ansible.builtin.meta: flush_handlers

- name: Ensure WireGuard enabled and started
  ansible.builtin.systemd:
    name: "{{ wireguard_service_name }}"
    state: started
    enabled: true

- name: Ensure setting wireguard_pki_keep_future_user_add_ability, no old local keys on finish
  ansible.builtin.import_tasks: pki_on_disk.yml
