---
- name: Ensure the required directories exist
  ansible.builtin.file:
    dest: "{{ item }}"
    state: directory
    recurse: true
  with_items:
    - "{{ wireguard_pki_path }}/preshared"
    - "{{ wireguard_pki_path }}/private"
    - "{{ wireguard_pki_path }}/public"
  delegate_to: localhost
  become: false
  when: wireguard_enabled
  tags:
    - setup-all
    - wireguard

- name: Ensure wireguard installed
  ansible.builtin.apt:
    name: wireguard
    state: present
    update_cache: true
  when: wireguard_enabled
  tags:
    - setup-all
    - wireguard

- name: Set OS specific facts
  ansible.builtin.set_fact:
    service_name: "wg-quick@{{ wireguard_interface }}"
  tags: always

- name: Import keygeneration tasks
  ansible.builtin.import_tasks: keys.yml
  when: wireguard_enabled
  tags:
    - setup-all
    - wireguard
    - update-users

- name: Import configuration tasks
  ansible.builtin.import_tasks: config.yml
  when: wireguard_enabled
  tags:
    - setup-all
    - wireguard
    - update-users

- name: WireGuard enabled and started
  ansible.builtin.systemd:
    name: "{{ service_name }}"
    state: started
    enabled: true
  when: wireguard_enabled
  tags:
    - setup-all
    - wireguard

- name: Delete the PKI directory
  ansible.builtin.file:
    path: "{{ wireguard_pki_path }}"
    state: absent
  become: false
  delegate_to: localhost
  when:
    - not store_pki
    - not pki_in_tmpfs
    - wireguard_enabled
  tags:
    - setup-all
    - wireguard

- name: Force all notified handlers to run at this point, not waiting for normal sync points
  ansible.builtin.meta: flush_handlers
  tags:
    - setup-all
    - wireguard
