---
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/blockinfile_module.html

# - name: Local folders
#   ansible.builtin.import_tasks: local_folders.yml
# - name: Reduce mtu
#   ansible.builtin.import_tasks: reduce_mtu.yml
# - name: Installed
#   ansible.builtin.import_tasks: installed.yml

- name: Facts, delete, add, new server
  ansible.builtin.import_tasks: facts.yml

- name: Facts, building blocks
  ansible.builtin.set_fact:
    wg_part_server: "1_server_part_{{ wireguard_interface }}.conf"
    wg_part_existing: "2_client_part_{{ wireguard_interface }}.conf"
    wg_part_new: "3_client_part_{{ wireguard_interface }}.conf"
    wg_parts_regexp: ".*part_{{ wireguard_interface }}.conf"

- name: Block server
  block:
    - name: New wg server
      ansible.builtin.import_tasks: make_new_server.yml
      when: wg_new_server

    # Extract server block, extract clients to keep block
    - name: Existing wg server
      ansible.builtin.import_tasks: make_existing_server.yml
      when: not wg_new_server


- name: Block clients, existing and new
  block:
    - name: Add starting ansible blockinfile marker for peers
      ansible.builtin.lineinfile:
        dest: "/etc/wireguard/{{ wg_part_server }}"
        line: "# vps_peers ANSIBLE MANAGED BLOCK"
        state: present

    - name: Keep existing clients
      ansible.builtin.import_tasks: make_existing_clients.yml
      when: not wg_new_server

    - name: Make new clients
      ansible.builtin.import_tasks: make_new_clients.yml

- name: Block endresult
  block:
    - name: Assemble all parts
      ansible.builtin.import_tasks: make_config_result.yml

    - name: Add closing ansible blockinfile marker for peers
      ansible.builtin.lineinfile:
        dest: "/etc/wireguard/{{ wireguard_interface }}.conf"
        line: "# vps_peers END ANSIBLE MANAGED BLOCK"
        state: present

# - name: Force all notified handlers to run at this point, not waiting for normal sync points
#   ansible.builtin.meta: flush_handlers

# - name: Ensure WireGuard enabled and started
#   ansible.builtin.systemd:
#     name: "{{ wireguard_service_name }}"
#     state: started
#     enabled: true
