---

- name: Ensure wireguard installed
  ansible.builtin.apt:
    name: wireguard
    state: present
    update_cache: true

- name: Shell scripts present
  ansible.builtin.include_tasks: modify/scripts.yml

- name: Facts as base for all further role processing
  ansible.builtin.include_tasks: facts.yml

- name: Start applying changes
  ansible.builtin.include_tasks: modify.yml
  when: wg_modify

- name: Ensure handlers run now
  ansible.builtin.meta: flush_handlers

- name: Ensure WireGuard enabled and started
  ansible.builtin.systemd:
    name: "{{ wireguard_service_name }}"
    state: started
    enabled: true
