---

# Files are assembled in string sorting order
- name: Assemble all files into a new server config
  ansible.builtin.assemble:
    src: "{{ wireguard_parts_path }}"
    dest: "{{ wireguard_server_conf }}"
    mode: "0600"
