---

- name: New wg server, retrieve keys
  ansible.builtin.shell: vps_wg_server_keys
  register: wg_serverkeys
  changed_when: wg_serverkeys.changed
  args:
    executable: bash

# TODO multiple vpn
- name: Fact, add server config to internal dictionary
  ansible.builtin.set_fact:
    wg_server: "{{ wg_server | default({}) | combine(\
                { 'ip': ip, 'ipv6': ipv6, 'port': port, 'key': key, 'pubkey': pubkey }) }}"
  vars:
    ip: "{{ wireguard_network_ipv4 | ansible.utils.ipaddr('1') }}"
    ipv6: "{{ wireguard_network_ipv6 | ansible.utils.ipaddr('1') if vps_ipv6_support else '' }}"
    port: "{{ wireguard_port }}"
    key: "{{ wg_serverkeys.stdout_lines[0] }}"
    pubkey: "{{ wg_serverkeys.stdout_lines[1] }}"
  no_log: true

- name: Create file containing only the server config
  ansible.builtin.template:
    src: server.conf.j2
    dest: "/etc/wireguard/{{ wg_part_server }}"
    mode: "0600"
