---

- name: Copy existing conf file to wg_part_server
  ansible.builtin.copy:
    src: "{{ wireguard_server_conf }}"
    dest: "{{ wg_part_server }}"
    remote_src: true
    mode: 0600

- name: Delete the peers block, keeping only the server block
  ansible.builtin.blockinfile:
    path: "{{ wg_part_server }}"
    marker_begin: "{{ _marker }}"
    marker_end: "{{ _marker }} END"
    block: ''
  vars:
    _marker: vps_peers
