---
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/blockinfile_module.html

- name: Folders in use
  ansible.builtin.include_tasks: modify/folders.yml
- name: Facts, building parts
  ansible.builtin.set_fact:
    wg_part_host: "{{ wireguard_parts_path }}/1_host_{{ wireguard_interface }}.conf"
    wg_part_new: "{{ wireguard_parts_path }}/2_new_{{ wireguard_interface }}.conf"

- name: New host
  ansible.builtin.include_tasks: modify/host_new.yml
  when: wg_new_host

- name: Existing host
  ansible.builtin.include_tasks: modify/host_existing.yml
  when: not wg_new_host

- name: Add peers
  ansible.builtin.include_tasks: modify/peers_add.yml
  when: wg_peers_to_add

# Files are assembled in string sorting order, overwrites destination
- name: Assemble all files into a host config
  ansible.builtin.assemble:
    src: "{{ wireguard_parts_path }}"
    dest: "{{ wireguard_host_conf }}"
    mode: "0600"
  notify:
    - Remove parts
    - Restart wireguard

# - name: Peers delete locally
#   ansible.builtin.stat:
#     path: "{{ wireguard_config_path }}{{ item.0 }}.{{ item.1 }}"
#   loop: "{{ wg_peers_to_delete | product(['conf', 'png']) }}"
#   register: _stat_result

# - name: Peers delete debug locally
#   ansible.builtin.debug:
#     msg: "{{ _stat_result }}"
# - name: Peers delete locally
#   become: false
#   ansible.builtin.file:
#     path: "{{ wireguard_config_path }}{{ wg_peer.name }}.conf"
#     state: absent
