---

# on change, copy changed server stdout result to a file on the ansible controller
# then, on server, create a new lock file
# notice the content being "stdout"...
- name: Save private keys
  ansible.builtin.copy:
    dest: "{{ wireguard_pki_path }}/private/{{ item['item'] }}"
    content: "{{ item['stdout'] }}"
    mode: "0600"
  no_log: "{{ wireguard_no_log | bool }}"
  when: item.changed
  with_items: "{{ wg_genkey['results'] }}"
  delegate_to: localhost
  become: false

- name: Touch private lock files
  ansible.builtin.file:
    dest: "/etc/wireguard/private_{{ item }}.lock"
    state: touch
    mode: "0644"
  with_items:
    - "{{ wireguard_users }}"
    - "{{ wireguard_host_ip }}"
